### ISSUE TITLE
Add timelength between latest data vs Current time

### ISSUE THREAD

**Issue by dargh1** [tananaev/traccar-web#101]
Hi, Tananaev,

1. In "STATE" windows there is already field called "time". Could you add timelength/time diference between this 'time' (the latest data sent to server by tracker) vs current time (i.e. 2 seconds ago, 2 days ago, 35 days ago, etc).

This is very useful small feature to easily monitor the performance of the tracker esp. if we have many trackers; such as: to know whether the SIM card is damage or out of balance, has connection problem, etc. 

2. Is there any field that I can use to store the phone number info? it would be nice and very helpful to have it stored in the server. 

Best
Dargh

**Comment by tananaev** [comment]
Device status including last update time will be available in the next release.
