### ISSUE TITLE
Submitted Patch for WEB service calling by traccar

### ISSUE THREAD

**Issue by hunterino** [tananaev/traccar-web#110]
I submitted a patch that allows the traccar data to be pushed to an external web service.  Do you plan on integrating it into your system?  I have several other features I would like to contribute, but I just want to make sure I am following you expected process.
Michael

**Comment by tananaev** [comment]
Old web interface is obsolete. Please use other bug tracker if this is still applicable:

https://github.com/tananaev/traccar/issues
