### ISSUE TITLE
Traccar development environment setup

### ISSUE THREAD

**Issue by ipozom** [tananaev/traccar-web#122]
Hello, My name is Ivan and i'm interested in your traccar open source implementation. Currently, i'm trying to seting up my development environment on my desktop, but i was not able to do this succesfully. I have eclipse JEE 3.7 (indigo) with JWT plugin, i generated the war file (traccar-web.war) but when i put this file on the traccar directory instalation the portal is not being displayed. The error got on chrome development tool is 404 with nocache.js file. I think is a missconfiguration of the classpath when the classes are generated. On the other way, could you give me your current eclipse and GWT version that you are using to develop ?.  I will appreciate your help in order to solve this issue. Thanks and regards.

**Comment by tananaev** [comment]
New web interface doesn't require any special environment set-up as it's written in pure JavaScript.
