### ISSUE TITLE
Blank page on attempted access to demo.traccar.org.

### ISSUE THREAD

**Issue by nbonniere** [tananaev/traccar-web#123]
If computer used doesn't have Java/JRE installed, only a blank page appears making it look like nothing is working for new people trying the demo who then just give up and move on. I almost gave up, but was interested in Android client and investigated further and figured out eventually why I got a blank page.

I suggest you detect the issue and provide a message that Java/JRE is needed with a link to do so, instead of ending up with a blank page.

**Comment by tananaev** [comment]
New versions are much more stable and this shouldn't happen any more.
