### ISSUE TITLE
Draw line between positions markers

### ISSUE THREAD

**Issue by Jeferex** [tananaev/traccar-web#129]
Hi Tananaev, I am customizing traccar to my needs and I want to show a line while new positions are shown. 
I've seen in MapPositionRenderer.java https://github.com/tananaev/traccar-web/blob/master/src/org/traccar/web/client/view/MapPositionRenderer.java#L92 You remove the oldMarker and put the newOne. What does new and old marker mean?

What I've done is delete the line where you remove the marker and Red Markers are shown in map. It is OK. However I would like to show a line between markers. Is it possible?

I tried to put oldMarker and newMarker LatLong to a Points Array and then draw the line  but no success.

I think there should be an empty array containing oldMarkers and then draw a line between newMarker and array.size() -1 so the line is shown.

Can you help me with this? Thanks in advance.

**Comment by tananaev** [comment]
Old web interface is obsolete. If you have something for the new UI, please create a new thread in the other issue tracker:

https://github.com/tananaev/traccar/issues
