### ISSUE TITLE
GPS LOCATION set to zero

### ISSUE THREAD

**Issue by lenovo7** [tananaev/traccar-web#133]
how can I configure this problem every time I do the command "position" on the GPS it gives me the  Latitude:0000000N, Longitude:000000E and also with the time and date they are not set to current :(( Anyone can help me fix this problem I didn't solve this for a couple of days.

for my GPS command this is I follow:

GPS Vehicle Tracker
User Manual
1.	Set Device ID Number:
This command is used only for GPRS communication. In order to identify the device in the platform, set a device ID(preferably use sim number) for every device. Send SMS “number+tracker ID number” to the tracker. For example “number39171234567”.
number639266944676
2.	Set APN:
In order to send GPS data to IP address, set the mobile network Access Point Name (APN). If the APN is not known, consult the local network service supplier. The format to set APN is “APN+password+<space>+apn value”.  Send SMS “APN123456 internet.globe.com.ph” to the device and the device will reply SMS “Set APN ok.”
apn123456 http.globe.com.ph
3.	Modify IP address and port:
The IP address and port of the tracker can be modified and data can be transferred to other platform. Send SMS “IP+<ip address>+PORT+port<value>” to the device. If the platform’s IP address and port is 122.52.118.154 and 8833, send SMS “ip122.52.118.154port8833” to the tracker. It will reply “set IP address and PORT ok.” after this, the device will send GPS data to this IP and Port.
ip122.52.117.85port5002
4.	Setting the device modes to “web”:
Set-up: Send SMS “web+password” to device. send SMS “web123456” to the device, the device will reply SMS “set web ok”.
web123456
5.	Auto Track Interval:
Send SMS “at30sum5” to the device, it will reply “Auto track set ok.” and report a Geo-info at 30 seconds intervals for 5 times: The max interval is 65535 seconds. You can send “at30sum0” for heaps of times. Send “noat123456” to the tracker, it will reply “Cancel auto track ok.” and the tracker will stop send messages. For now set device auto track interval to "at30sum0".
at10sum0
6.	Initialization:
After setting the required configuration, send “Begin+password” via SMS to the unit, it will reply “begin ok “and it will initialize all the settings. 
begin123456

and this is my device:
http://www.gpstracking.co.in/documents/TK103.pdf

**Comment by karthikindia** [comment]
how did u solve this ?
