### ISSUE TITLE
 I'm trying to translate into Spanish

### ISSUE THREAD

**Issue by fabover** [tananaev/traccar-web#136]
Hello, I'm trying to translate into Spanish website Traccar, and modify the xml of the following location: WEB-INF \ classes \ org \ traccar \ web \ client \ view and compile with eclipse, but nothing changes everything stays in English. I modify other files to translate? You can tell me on which files I should modify and your location? Thank you very much, the system works perfect for me, only want to change the language. Excuse my English, I'm Uruguayan.

**Comment by tananaev** [comment]
I need help with translating new web interface. If you are interested, please translate all text (within double quotes) in the following file and send it to me via pull request or just email (see profile):

https://github.com/tananaev/traccar/blob/master/web/l10n/en.js

**Comment by gabrielcz** [comment]
We can help with!!!

Enviado desde mi iPhone

**Comment by gabrielcz** [comment]
2015-07-10 8:57 GMT-03:00 Gabriel Czerniecki <gabrielcz@gmail.com>:

> We can help with!!!
>
> Enviado desde mi iPhone
>
> El 10/7/2015, a las 4:23, Anton Tananaev <notifications@github.com>
> escribió:
>
> I need help with translating new web interface. If you are interested,
> please translate all text (within double quotes) in the following file and
> send it to me via pull request or just email (see profile):
>
> https://github.com/tananaev/traccar/blob/master/web/l10n/en.js
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tananaev/traccar-web/issues/136#issuecomment-120264473>
> .
>
>


-- 
.::.gabrielcz.::.

**Comment by cgarbero** [comment]
var strings =  {    shared_loading: 'Cargando...',    shared_save: 'Grabar',    shared_cancel: 'Cancelar',    shared_add: 'Agregar',    shared_edit: 'Editar',    shared_remove: 'Borrar',    shared_remove_confirm: 'Borrar item?',
    error_title: 'Error',    error_unknown: 'Error Desconocido',
    user_name: 'Nombre',    user_email: 'Email',    user_password: 'Contraseña',    user_admin: 'Admin',
    login_title: 'Ingresar',    login_register: 'Registrar',    login_login: 'Ingresar',    login_failed: 'Direccion de correo o Contraseña Incorrecta',    login_created: 'Nuevo Usuario a Sido Registrado',    login_logout: 'Salir',
    device_dialog: 'Dispositivo',    device_title: 'Dispositivos',    device_name: 'Nombre',    device_identifier: 'Identificador',
    settings_title: 'Preferencias',    settings_user: 'Cuenta',    settings_server: 'Servidor',    settings_users: 'Usuarios',
    report_title: 'Reportes',    report_device: 'Dispositivos',    report_from: 'Desde',    report_to: 'a',    report_show: 'Mostrar',    report_clear: 'Limpiar',
    position_time: 'Hora',    position_valid: 'Valida',    position_latitude: 'Latitud',    position_longitude: 'Longitud',    position_altitude: 'Altitud',    position_speed: 'Velocidad',    position_course: 'Curso',    position_address: 'Direccion',    position_protocol: 'Protocolo',
    server_title: 'Preferencias Servidor',    server_zoom: 'Zoom',    server_registration: 'Registrar',
    map_title: 'Map',
    state_title: 'Estado',    state_name: 'Parametro',    state_value: 'Valor'};

Carlos Gabriel GarberoAnalista en Sistemas - Técnico en Computación Celular: 0381-153307945

Date: Fri, 10 Jul 2015 00:23:10 -0700

**Comment by tananaev** [comment]
Thanks. Here is a demo (login: admin - admin): http://dev.traccar.org/?locale=es

Please check and let me know if something needs to be changed.

**Comment by gabrielcz** [comment]
Some things must to be changed, I test it at restaurant, weekends will send you an email :). Regards, thanks you 

Enviado desde mi iPhone

**Comment by tananaev** [comment]
Starting from version 3.1 Traccar supports localization and includes a few popular languages already. Anyone who is interested in helping with adding new languages or improving existing translations please read following page:

https://www.traccar.org/blog/traccar-localization/
