### ISSUE TITLE
An internal error occurred during: "traccar - GWT Compile". java.lang.NullPointerException

### ISSUE THREAD

**Issue by fabover** [tananaev/traccar-web#137]
When I try to compile with eclipse, going to the GWT compile button proyect, I get the following error: An internal error occurred During "traccar - GWT Compile".
java.lang.NullPointerException. I thought I was bad for some modification on my part, so I opened the project and try to compile unmodified, but I get the same error. Can you help please?

**Comment by tananaev** [comment]
Old web interface is obsolete. If new web interface has same/similar issue, please report it here:

https://github.com/tananaev/traccar/issues
