### ISSUE TITLE
Devices Created from the backend wont showup.

### ISSUE THREAD

**Issue by hussainnagri** [tananaev/traccar-web#142]
I am inserting new devices directly into the backend of traccar, The problem is that this added devices wont show up unless I completely clear all the cache and cookies and then log in again. how to overcome this limitation ?

**Comment by tananaev** [comment]
Shouldn't be a problem with the new web interface.

**Comment by tananaev** [comment]
Also, new version include API to add users and devices:

https://www.traccar.org/traccar-api/
