### ISSUE TITLE
ADD colored balls that indicates device's comunicates state.

### ISSUE THREAD

**Issue by study3ggsm** [tananaev/traccar-web#153]
I noticed that when the device sends GPS cordinates void because he has not picked up the gps point out, the software TRACCAR does not report anything. In this way the user is not able to understand even if the GPS device communicates or less.
Would it be possible to add a function (like a ball that is colored green or red) that indicates, however, that the device communicates?
Thank you very much.

**Comment by tananaev** [comment]
This feature is planned for the next release.
