### ISSUE TITLE
User name or password is invalid

### ISSUE THREAD

**Issue by vogelgis** [tananaev/traccar-web#155]
Login does not work. User name and password is definitly correct, I cann login to the mysql database, but the web login does not work.
In the mysql database I can the see that the database is working. Any hints, the only thing I have changed is the admin password of the track schema and the root password of the mysql database

**Comment by tananaev** [comment]
Old web interface is obsolete. If new web interface has same/similar issue, please report it here:

https://github.com/tananaev/traccar/issues
