### ISSUE TITLE
Updates

### ISSUE THREAD

**Issue by zikizira** [tananaev/traccar-web#156]
Thinking about the ones that can't edit and compile the traccar-web to make it easier or customized to their needs (including me), I would like to know if the version released on www.traccar.org is the same that is updated on github or if I want the new functionalities or bug fixes available I have to recompile the source code? 
If it's not, is there an easiest way to recompile with the new functionalities?

**Comment by tananaev** [comment]
Build process is much easier now:

https://www.traccar.org/build/
