### ISSUE TITLE
Improve Database schema

### ISSUE THREAD

**Issue by Jeferex** [tananaev/traccar-web#16]
Is it possible to add a column to all tables that records the date and time the update or insertion was made?

And one last question, can I do a POST from another page (in PHP) and do the login process and take me directly to the map? If it is not posible, how can I customize the traccar web application or what software do I need in order to do so?

**Comment by tananaev** [comment]
Database schema completely changed in version 3.0:

https://github.com/tananaev/traccar/blob/master/debug.xml#L53
