### ISSUE TITLE
Blank LOGIN page

### ISSUE THREAD

**Issue by Gioz79** [tananaev/traccar-web#181]
Hi,
installed traccar some time ago and it worked like a charm. After some days I didn't touch it because of being busy on other stuff, now it presents me a blank login page telling me to enable javascript (yes, it's currently enabled). I tried IE, Chrome, FFox; same results.
I've read issue #150 but I think my problem is different, since I can't even login. Anyway I'm sure the scripts and css files are reachable from both the client and the server.
I already tried to reinstall traccar, cleaning up WINDOWS/Temp/jetty..., and cleaning up browsers cache, all without success.

Here's the page presented to me:
<!doctype html>
<html>
  <head>
    <meta http-equiv="content-type" content="text/html; charset=UTF-8">
    <title>Traccar</title>

    <link rel="stylesheet" type="text/css" href="traccar/reset.css" />

    <script src="http://www.openlayers.org/api/OpenLayers.js"></script>
    <script src="http://www.openstreetmap.org/openlayers/OpenStreetMap.js"></script>
    <script src="http://maps.google.com/maps/api/js?v=3&amp;sensor=false"></script>
    <script type="text/javascript" src="traccar/traccar.nocache.js"></script>

        
    <style type="text/css">
      .olControlAttribution { bottom: 5px !important; }
    </style>

  </head>
  <body>
    <noscript>
      <div>
        Your web browser must have JavaScript enabled
        in order for this application to display correctly.
      </div>
    </noscript>
  </body>
</html>

tracker-server.log
INFO: Starting server...
INFO: Operating System name: Windows 2003 version: 5.2 architecture: x86
INFO: Java Runtime name: Java HotSpot(TM) Client VM vendor: Sun Microsystems Inc. version: 19.1-b02
INFO: Memory Limit heap: 247mb non-heap: 118mb

wrapper.log
WrapperManager: Initializing...
INFO:oejs.Server:jetty-8.1.14.v20131031
INFO:oejw.WebInfConfiguration:Extract jar:file:/C:/Programmi/Traccar/traccar-web.war!/ to C:\WINDOWS\Temp\jetty-0.0.0.0-8082-traccar-web.war-_-any-\webapp
INFO:oejw.StandardDescriptorProcessor:NO JSP Support for /, did not find org.apache.jasper.servlet.JspServlet
INFO:oejs.AbstractConnector:Started SelectChannelConnector@0.0.0.0:8082

Thank you so much,
Ivan

Edit: sorry for the bad formatting, it's my first time here

**Comment by tananaev** [comment]
Old web interface is obsolete. If new web interface has same/similar issue, please report it here:

https://github.com/tananaev/traccar/issues
