### ISSUE TITLE
How can I compile de Source Code..?

### ISSUE THREAD

**Issue by sademene** [tananaev/traccar-web#182]
Hi;
Sorry but i'm newbie in this kind of things, i have a very basic programing skills (and 
Enghlish skills too jeje), I just change a tiny part in the source code with eclipse but now I don't know how compile it .
If someone can help please, ;)
thank's a lot!!!

**Comment by tananaev** [comment]
Instructions for building new versions of Traccar:

https://www.traccar.org/build/
