### ISSUE TITLE
reset.css not found error

### ISSUE THREAD

**Issue by boratevfik** [tananaev/traccar-web#183]
Hi,

     I get the following error, when opening the page local:8082    :

Remote Address:127.0.0.1:8082
Request URL:http://localhost:8082/traccar/reset.css
Request Method:GET
Status Code:404 Not Found
Request Headers view source

There are missing directories and files in localhost 

What could be wrong here?
![localhost_missing_directories](https://cloud.githubusercontent.com/assets/7912732/3301165/8a01e15c-f628-11e3-925b-f77312b5b8c9.PNG)

I had not used GWT compilation, now trying that.
Yes the problem is now resolved.

Best regards,
Bora.

**Comment by tananaev** [comment]
Old web interface is obsolete. If you have issues with new web interface please report them in the other bug tracker:

https://github.com/tananaev/traccar/issues
