### ISSUE TITLE
Conect to alternative database

### ISSUE THREAD

**Issue by sademene** [tananaev/traccar-web#185]
Hi, 
Thank you for you amazing work!

Can I conditionate the conection of the traccar server to a mysql database?
I mean: if can't conect to a remote database, then conect to a local host?

how can I do it?

Thank's

**Comment by tananaev** [comment]
Link with information for the new versions of Traccar:

- MySQL - https://www.traccar.org/mysql/
- MS SQL - https://www.traccar.org/ms-sql/
- PostgreSQL - https://www.traccar.org/postgresql/
