### ISSUE TITLE
Laipac S911 Lola not showing in Traccar Web

### ISSUE THREAD

**Issue by Geert1969** [tananaev/traccar-web#187]
Hello,

We are using a Laipac S911 Lola. It's configured to send the GPS coordinates to the public IP address of our server where Traccar is installed on. We use port 5048.
The firewall receives traffic and accepts it. But it doesn't show in Traccar Web.
What could the reason be that it's not showing?
You can find the log files here:
https://dl.dropboxusercontent.com/u/21241437/tracker-server.log
and
https://dl.dropboxusercontent.com/u/21241437/wrapper.log.20140624
I hope you can help us in solving this issue.
Best Regards,
Geert

**Comment by tananaev** [comment]
Latest version include options to set default location and zoom for the whole server or each user separately.
