### ISSUE TITLE
Car fleet

### ISSUE THREAD

**Issue by momo54180** [tananaev/traccar-web#194]
Hello,
I have tested Traccar, and its really a great job !
I have only one GPS Tracker, type TK103.
I would like to try Traccar with more vehicules......
If someone could send his infos on my IP adress : 
82.227.186.236 (in France) and give me his IMEI (not the password !), I could try it ....
like a company, with a car fleet....(only for a few days !)
Thanks for you answer.
Have a nice day
Christian

**Comment by tananaev** [comment]
There is a new performance testing script available that can simulate any number of devices:

https://github.com/tananaev/traccar/blob/master/tools/test-performance.py
