### ISSUE TITLE
Multiple language support

### ISSUE THREAD

**Issue by custodium** [tananaev/traccar-web#197]
Hello, there is an easy way to translate traccar interface to another language?

BTW: I think that can be a good idea for future versions implement an xml based system to add new languages without compiling.

Best regards.

**Comment by tananaev** [comment]
Starting from version 3.1 Traccar supports localization and includes a few popular languages already. Anyone who is interested in helping with adding new languages or improving existing translations please read following page:

https://www.traccar.org/blog/traccar-localization/
