### ISSUE TITLE
Web Server

### ISSUE THREAD

**Issue by cercata** [tananaev/traccar-web#208]
Is it posible to run the web interface from "Apache Web Server", "JBoss" or another ?

I guess it will have better performance, since only the traccar app will be run on javavm, the server itself will be native ?

Anyone has done it ? Is there a performance gain ?

**Comment by xizoaziz** [comment]
HI cercata

could you please tell me how to deploy to Tomcat i tried it but always give me FAIL - Application at context path /traccar-web-2.12-SNAPSHOT could not be started

is there any required library i have to add first or any steps i must follow ??

thanks

**Comment by cercata** [comment]
I deployed it manually. I'll check tomorrow how exactly.

**Comment by cercata** [comment]
After generating traccar-web, I move/copy the folder manually:

cp -R ./target/traccar-web-2.11-SNAPSHOT /opt/traccar-web

Then I added the file traccar.xml to the "/etc/tomcat7/Catalina/localhost/" folder:

<?xml version="1.0" encoding="UTF-8"?>
<Context path="/traccar"
        docBase="/opt/traccar-web"
        antiResourceLocking="false" privileged="true">
</Context>

Then I restart tomcat and Voila, it works.

**Comment by xizoaziz** [comment]
thanx  cercata 

best regards
