### ISSUE TITLE
getLatestPositions performance

### ISSUE THREAD

**Issue by cercata** [tananaev/traccar-web#209]
mysqld is consuming a lot of CPU now that I have 700.000 positions in the DB.
It looks the problem is in the getLatestPositions() QUERY.

If I execute it in mysql-workbench it takes 1 second:
SELECT * FROM traccar.positions x WHERE x.id IN (SELECT latestPosition_id FROM traccar.devices y WHERE y.id IN (1,2,3,4));

But, if I split the query into 2 separte querys, each one executes in 0 seconds.
SELECT * FROM traccar.positions x WHERE x.id IN (825202, 825208, 825214,825233);
SELECT latestPosition_id FROM traccar.devices y WHERE y.id IN (1,2,3,4);

It looks like mysql is not using the index on positions.id when we put a second select in the "IN".

¿ Any ideas why ?

It looks like it's a mysql/InnoDB "FEATURE":
http://stackoverflow.com/questions/17819655/mysql-nested-query-speed

It could be a nice idea to use postgres. Anyway, I'm gonna see if we can reformulate the query without being nested.

**Comment by tananaev** [comment]
In the new web interface all database queries are in the config file and they are more optimal than old automatically generated ones. If there are performance problems with new UI, please report on the other bug tracker:

https://github.com/tananaev/traccar/issues
