### ISSUE TITLE
When is the estimated time of release of the modified version? (Pure Java based Web)

### ISSUE THREAD

**Issue by ccoronadobriceno** [tananaev/traccar-web#220]
Hi..
I would just like to know if you have an estimated release time for the new web version of traccar, I was following the progress graph and saw that you were implementing a lot of the things that I was needing, especially the map tag of each transmitter. I was also wondering if you were going to implement geozoning and grouping of transmitters. 
I want to congratulate you on this great piece of software and the time and effort you are putting towards it, I am no programer so there is not much I can help with, but it would be nice if you had a plugin sistem where the people asking for help on special features would include them if they are succesfull as a plugin.. 
Well again thanks for this system.

**Comment by tananaev** [comment]
Official Traccar now includes pure JavaScript-based interface.
