### ISSUE TITLE
Copy data error

### ISSUE THREAD

**Issue by gonzalezsergio** [tananaev/traccar-web#233]
Hello, I am trying to copy the devices from traccar to our backoffice through triggers but I had a mistake in that I have executed the trigger from our base so it created a new record in the devices table traccar.
I've eliminated through phpmyadmin but now at the time of executing the trigger from traccar always gives me the same result "Device With This Unique ID already exists"
I appreciate if you can guide me.
Sergio.-

**Comment by tananaev** [comment]
Old web interface is obsolete. If new web interface has same/similar issue, please report it here:

https://github.com/tananaev/traccar/issues
