### ISSUE TITLE
How does the application work ?

### ISSUE THREAD

**Issue by TienHung1985** [tananaev/traccar-web#234]
Firstly , this is the amazing application I've seen.

I'm a embedded developer so not yet familiar with web based Apps. 
So I have a  question: 
how does data automatically updated on browser whenever server side - database is updated?
(device send data to server, server store it on its database -> how the browser know to render web page because at that time the connection closed)

Thanks in advance!

**Comment by tananaev** [comment]
Staring from version 3.0 Traccar implements long-polling for instant location updates.
