### ISSUE TITLE
Authentication Integration

### ISSUE THREAD

**Issue by rpdubose** [tananaev/traccar-web#237]
Very cool app.  Interested in using & contributing.  Question...I'd like to attempt to integrate my websites login w/ traccar & only require a single logon.  Currently what I have working is a logon to my website & then the traccar login/register modal is shown.  I'd like the user to have a single logon but I can't find the file(s) where traccar is surfacing their logon.  If you can point me to the file that surfaces that, I should be able to do the rest.  Thanks.

**Comment by nwohaibi** [comment]
@tananaev  @vitalidze  Thanks for the great job.

**Comment by tananaev** [comment]
New version of Traccar include API that you can use for authentication:

https://www.traccar.org/traccar-api/
