### ISSUE TITLE
quetion

### ISSUE THREAD

**Issue by umeshbichukale** [tananaev/traccar-web#241]
hiii,
i am editing this project in my windows 64 bit and in eclipse(Kepler) but i am confused from where to start editing and how to import this project and which other software , jar files are required please guide me in detail.
Thanks in advance

**Comment by umeshbichukale** [comment]
Dear sir,
   I am Umesh from india.i need to know can i develop this traccar
application by using Struts framework and Hibernate.please give me some
idea or suggestion to how to develop this application using Struts
framework.

**Comment by tananaev** [comment]
Sorry, I don't know much about Struts.
