### ISSUE TITLE
NEED HELP

### ISSUE THREAD

**Issue by cypherbond** [tananaev/traccar-web#243]
Dear Anton Tananaev,
Your work is awsome and I'm very much interested in implementing it on my own website. I'm complete newbie in programming and hardly know linux. I have following qestions:
1)  I have domain name from godaddy and I'm planning to buy webspace from them too. There are 2 options for webspace : windows or linux. Which one is prefereable?
2) Should I buy static IP for tracking?
3) What installations are to be carried out on the server or should I copy the files extracted from zip file?
4) Can you provide me zip file with traccar folder and file structure which when extracted on server will easily start the traccr?
Please explain me in detail.

**Comment by tananaev** [comment]
1) You need a VPS to host Traccar. Linux is probably better option because it is usually cheaper than Windows.

2) Yes, you need a static IP for tracking.

3) For Linux: http://www.traccar.org/docs/linux.jsp.

4) You have to use installer.

**Comment by cypherbond** [comment]
Thanks for quick reply. May be my questions are very basic for masters like you but I got very short time doing this for my new project to study everything. I'm struggling to implement this for last 2 days with no success. It runs very easily on my local computer on both windows and ubuntu machines but not on server. You specified following points for installation
    Run traccar.run (sudo ./traccar.run)
    Start daemon (sudo /opt/traccar/bin/traccar start)
When I uploaded traccar.run file to public folder on webspace, I find no tool to run such commands. Somewhere I found technical help in which I had to use SSL connection through terminal of my local computer to execute above commands on server. But it refused to establish the connection. What can I do to make installer run with this command on webspace? Is there any tool that can be used?

**Comment by tananaev** [comment]
What is the "webspace"? Is it Windows or Linux? If Linux, you need to run those commands through SSH.

**Comment by cypherbond** [comment]
Dear Sir, I am talking about web host based on linux. I tried to pass ssh command but it refuses connection. What should I do?

**Comment by tananaev** [comment]
As I said you need a VPS. Regular web hosting is not enough.
