### ISSUE TITLE
show address in archive/web

### ISSUE THREAD

**Issue by aacable** [tananaev/traccar-web#245]
How can I show ADDRESS in archive view (or also in web at every point it updates like in opengts)

I read this link but sorry I couldn't understand, which file need to be edited in order to show address colum?
https://github.com/tananaev/traccar-web/blob/master/src/org/traccar/web/client/view/ArchiveView.java#L125

**Comment by vitalidze** [comment]
It's already added in my fork. Here is how to add it https://github.com/vitalidze/traccar-web/issues/17

Here is a brief description on how to use it: http://traccar.litvak.su/features/address-column-in-archive-grid.html

**Comment by tananaev** [comment]
Implemented in official Traccar version as well.
