### ISSUE TITLE
Traccar Update Frequency and Many 

### ISSUE THREAD

**Issue by aacable** [tananaev/traccar-web#246]
Dear Sir,

I have a strange problem. I have set traccar-client (my android mobile set) update frequency to 60 seconds. now its updating data on every minute. but the issue is that it keep updating the data and showing so many pointer. Even if I am at home, its adding many pointers at same place or around. so its hard to see the exact location as seen in the image attached. How can I set client to not to update if there is no movement or the device is not moving. What is your recommendation or views in this regard?

 
![1](https://cloud.githubusercontent.com/assets/6860656/5646207/3f0bb0ec-969b-11e4-993c-145edb38bbd1.PNG)

 
In this image I am at my place and the mobile is at my desk. and see the result , so many pointers :s how to reduce them

Regards,
SYED JAHANZAIB

**Comment by tananaev** [comment]
There is no such option in the app, but you can enable filtering on the server side (filter.distance int the config file).

**Comment by tananaev** [comment]
More info on configuration options:

https://www.traccar.org/configuration-file/
