### ISSUE TITLE
Logging into Traccar from a remote PHP program

### ISSUE THREAD

**Issue by dkenterprise100** [tananaev/traccar-web#248]
Hi All
   I was able to successfully compile and run the Traccar program. Thanks once again.

Now, my next queries are:

1. I have a PHP Client program on a separate server and Traccar on a separate server.
    I want to login directly from the PHP Client into Traccar and land directly on the GPS Maps page. 
For this which files and functions should I modify.

2. Also, I want to change the color of the Application to Yellow which files should I modify ?

Your help will be appreciated. TIA

Rgds,
 DK

**Comment by vitalidze** [comment]
1. [My fork](https://github.com/vitalidze/traccar-web) has [automatic login function](http://traccar.litvak.su/features/automatic-login.html). Also there is a RESTful API, which you may use to integrate map into your web site. But it requires some coding in javascript+html.

2. [Read about themes in GXT here](http://docs.sencha.com/gxt-guides/3/ui/theme/Themes.html)

**Comment by dkenterprise100** [comment]
Thanks vitalidze.
I have knowledge of javascript+html

**Comment by dkenterprise100** [comment]
Vitalidze,
    I downloaded your "traccar-web" zip file and tried opening in Eclipse but could not.
Eclipse gave error "Could not import project".  Please suggest how to open and compile

**Comment by vitalidze** [comment]
Here are [instructions](http://traccar.litvak.su/ide/eclipse.html), but they may not work, at least I haven't tried them for half of year or so. I am developing in [IntelliJ Idea](http://traccar.litvak.su/ide/idea.html), where it works just fine. Also I know that people using [NetBeans](http://traccar.litvak.su/ide/netbeans.html) also got it working.

**Comment by Hemendrajain** [comment]
Thanks Vitalidze. Will try and update you...

**Comment by Hemendrajain** [comment]
I am able to compile the code and it generated the corresponding 'war' file.

Now, my question is how do I run/install it.

I checked and ran the package.sh file (running on Ubuntu) but it did not do anything.

Can you give me the instruction of how to install and then run it...

**Comment by vitalidze** [comment]
Here is how to install updated `traccar-web.war` over existing traccar installation: http://traccar.litvak.su/installation.html

You can read about installation of official package here: http://www.traccar.org/docs/linux.jsp

**Comment by Hemendrajain** [comment]
Getting Issues:

On 32-bit Ubuntu
I was able to compile both traccar-web and traccar codes.
When I try to run http://localhost:8082, it gives me the following page

Directory: /
META-INF : 4096 bytes

What am I doing wrong ?

**Comment by vitalidze** [comment]
How did you built `traccar-web.war` file?

**Comment by Hemendrajain** [comment]
Vitali,
  I used IntelliIDEA and built YOUR code and obtained traccar-web.war

**Comment by vitalidze** [comment]
The proper way is to build it with maven. Please follow instructions here: http://traccar.litvak.su/building.html

**Comment by dkenterprise100** [comment]
Vitali,
  I installed 'mvnw' package and followed the above instructions..

Got error.

Log Snippet:
cmd ran: sanju@ubuntu:/media/vital/traccar-web$ ./mvnw -X package 

[INFO] Using 'UTF-8' encoding to copy filtered resources.
[DEBUG] resource with targetPath null
directory /media/vital/traccar-web/src/main/java
excludes []
includes [**/*.gwt.xml, **/*.ui.xml]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 2.057s
[INFO] Finished at: Wed Jan 14 01:46:07 PST 2015
[INFO] Final Memory: 7M/17M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-resources-plugin:2.6:resources (default-resources) on project traccar-web: Cannot create resource output directory: /media/vital/traccar-web/target/traccar-web-2.10-SNAPSHOT/WEB-INF/classes -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-resources-plugin:2.6:resources (default-resources) on project traccar-web: Cannot create resource output directory: /media/vital/traccar-web/target/traccar-web-2.10-SNAPSHOT/WEB-INF/classes
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:216)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:84)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:59)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.singleThreadedBuild(LifecycleStarter.java:183)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:161)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:317)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:152)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:555)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:214)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:158)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.apache.maven.wrapper.BootstrapMainStarter.start(BootstrapMainStarter.java:41)
	at org.apache.maven.wrapper.WrapperExecutor.execute(WrapperExecutor.java:150)
	at org.apache.maven.wrapper.MavenWrapperMain.main(MavenWrapperMain.java:53)
Caused by: org.apache.maven.plugin.MojoExecutionException: Cannot create resource output directory: /media/vital/traccar-web/target/traccar-web-2.10-SNAPSHOT/WEB-INF/classes
	at org.apache.maven.plugin.resources.ResourcesMojo.execute(ResourcesMojo.java:307)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:106)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
	... 26 more
Caused by: org.apache.maven.shared.filtering.MavenFilteringException: Cannot create resource output directory: /media/vital/traccar-web/target/traccar-web-2.10-SNAPSHOT/WEB-INF/classes
	at org.apache.maven.shared.filtering.DefaultMavenResourcesFiltering.filterResources(DefaultMavenResourcesFiltering.java:215)
	at org.apache.maven.plugin.resources.ResourcesMojo.execute(ResourcesMojo.java:301)
	... 28 more
[ERROR] 
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
sanju@ubuntu:/media/vital/traccar-web$

**Comment by antoniopaisfernandes** [comment]
Why is it trying to create "/media/vital/traccar-web/target...."

I do:

git clone https://github.com/vitalidze/traccar-web.git
cd traccar-web/
./mvnw clean package

and it works fine.

Regards,
Antonio Fernandes

**Comment by vitalidze** [comment]
Try running:

    ./mvnw clean package

I.e. add `clean` as command line argument.

**Comment by dkenterprise100** [comment]
Tried...Not working



See 'mvnw help <command>' for information on a specific command.
sanju@ubuntu:/media/vital/traccar-web$ ./mvnw clean package
[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building Traccar Web UI 2.10-SNAPSHOT
[INFO] ------------------------------------------------------------------------
Downloading: http://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-clean-plugin/2.5/maven-clean-plugin-2.5.pom
Downloaded: http://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-clean-plugin/2.5/maven-clean-plugin-2.5.pom (4 KB at 3.3 KB/sec)
Downloading: http://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-clean-plugin/2.5/maven-clean-plugin-2.5.jar
Downloaded: http://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-clean-plugin/2.5/maven-clean-plugin-2.5.jar (25 KB at 27.5 KB/sec)
[INFO] 
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ traccar-web ---
Downloading: http://repo.maven.apache.org/maven2/org/codehaus/plexus/plexus-utils/3.0/plexus-utils-3.0.jar
Downloaded: http://repo.maven.apache.org/maven2/org/codehaus/plexus/plexus-utils/3.0/plexus-utils-3.0.jar (221 KB at 95.7 KB/sec)
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ traccar-web ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 6.413s
[INFO] Finished at: Wed Jan 14 03:50:17 PST 2015
[INFO] Final Memory: 8M/20M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-resources-plugin:2.6:resources (default-resources) on project traccar-web: Cannot create resource output directory: /media/vital/traccar-web/target/traccar-web-2.10-SNAPSHOT/WEB-INF/classes -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

**Comment by vitalidze** [comment]
Then I believe something is wrong with permissions in `/media/vital/traccar-web/` folder. Please check that your user has permission to read and write to that folder and all subfolders. 

My guess is maybe you have done something with `sudo` and now that entire folder is owned by `root` user.

**Comment by dkenterprise100** [comment]
Sure. Will check and revert back...

**Comment by Hemendrajain** [comment]
I am able to compile the traccar-web sources using IntelliJ IDEA/.mvnw package ...it shows compiled successfully but did not create the traccar-web.war...

Where am I going wrong..

I also checked 'package.sh' in traccar-web directory

It reads...

mv war/WEB-INF/deploy/ tmp/
mv war/WEB-INF/lib/h2-* tmp/
jar cv -C war/ . > traccar-web.war
...

But I did not see any 'war' being created after mvnw package

**Comment by vitalidze** [comment]
You should look for `traccar-web.war` under `target` sub-folder.

`package.sh` is for non-maven version of project (which is the original one). Please don't use it with my fork.

**Comment by Hemendrajain** [comment]
Hi Vitaldize,
   I searched in "target" folder but could not locate "traccar-web.war".

Also, is there something to do with Maven version ?

I am using Maven2 right now which compiles properly...

**Comment by vitalidze** [comment]
I haven't tried with maven2. Maven wrapper, which is invoked by `mvnw`, is using maven3. I can say that I haven't any issues with .war file creation on many different machines. Are you running with `package` argument?

    mvn clean package

**Comment by Hemendrajain** [comment]
Sorry...it is Mavne 3.2

sanju@ubuntu:~/IdeaProjects/traccar-web$ mvn -V
Apache Maven 3.2.1 (ea8b2b07643dbb1b84b6d16e1f08391b666bc1e9; 2014-02-14T09:37:52-08:00)
Maven home: /usr/share/maven3
Java version: 1.7.0_71, vendor: Oracle Corporation
Java home: /usr/java/jdk1.7.0_71/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "2.6.32-38-generic", arch: "amd64", family: "unix"

**Comment by Hemendrajain** [comment]
Yes, I am running

./mvnw package

Also, tried

./mvnw clean package

**Comment by vitalidze** [comment]
Then please post full contents list of `target` folder after running `mvnw clean package` (it takes ~10 minutes on my machine).

**Comment by Hemendrajain** [comment]
Sure

**Comment by Hemendrajain** [comment]
Thanks Vitali/Tananaev...

The issue was related to infrastructure..I am able to build and run my program..
Issue resolved.
Thanks once again
