### ISSUE TITLE
How to update markers without reloading open layer map

### ISSUE THREAD

**Issue by 7hill** [tananaev/traccar-web#250]
Dear All,
   I have used marker layer with openlayer map. I could not able to update the marker list with reloading the map. I have to use map.updateSize() method to update the markers.

  Kindly help me, how to update markers without reloading the map?

Thanks in advance.

**Comment by tananaev** [comment]
If you want to update marker call `removeMarker(...)` first and then `addMarker(...)` to add a new one with updated location.

**Comment by 7hill** [comment]
Thanks for your reply. I need to remove all markers, so I used clearMarkers() to remove all markers and addMarker(...) to add new markers. The added new marker and cleared markers not updating in map without reloading it. Kindly suggest me to fix this issue.

Thanks,

**Comment by tananaev** [comment]
Try to remove them one by one and see if it works.

**Comment by 7hill** [comment]
I have tried to remove all markers one by one and added again, nothing workings.
Finally I destroyed the marker layers and added again with new markers. It's working fine.

Thanks,

**Comment by antoniopaisfernandes** [comment]
Btw tananaev (& others), do you know if there is a "super" layer that 'implements' both Vector and Markers layers/method/features?

I was trying to use only Markers for current markers, Vector for current vector and use a "new" layer for Archive (only 1 layer for markers and route/vector)...

Best regards,
Antonio Fernandes

**Comment by tananaev** [comment]
@7hill, removing markers one by one definitely works for me, so you must be doing something wrong.

@antoniopaisfernandes, I don't think there is a single layer for both markers and vectors, but it's better to check documentation.
