### ISSUE TITLE
any update of the new web interface?

### ISSUE THREAD

**Issue by gabrielcz** [tananaev/traccar-web#251]
Hi, are there any update about the new interface for traccar?
is the project start? can share a timeline if anyone have it?

regards,

GCZ

**Comment by tananaev** [comment]
I am working on design and reading books and articles about ExtJS. I don't have any timelines.

**Comment by gabrielcz** [comment]
So, ExtJS will be?
great! thanks...
regards,

2015-01-27 17:46 GMT-03:00 Anton Tananaev <notifications@github.com>:

> I am working on design and reading books and articles about ExtJS. I don't
> have any timelines.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tananaev/traccar-web/issues/251#issuecomment-71724511>
> .
>



-- 
.::.gabrielcz.::.

**Comment by bicho** [comment]
Hi, what do yout think about a fork with AngularJS,  Bootstrap 3, Jquery (Yeoman, Grunt, Bower).
regards,

**Comment by tananaev** [comment]
Which one?

**Comment by nwohaibi** [comment]
Hi @tananaev 

How about merging the RESTful API from https://github.com/vitalidze/traccar-web/ or creating some other JSON API?
Since separating the back-end from front-end would surly ease up the development.
I would certainly work on the front end of Traccar if it is purely built on top of JS/AJAX/HTML5.
e.g. http://aldalal.com/ (AJAX) and http://aldalal.com/map
Moreover, Java's GWT and ExJS are just horrible :)

and thanks again for the great work.

**Comment by tananaev** [comment]
I am planning to use ExtJS. What are the alternatives?

**Comment by nwohaibi** [comment]
All will have to have an HTTP API from the traccar-server.

**Comment by nwohaibi** [comment]
I think Expanding upon traccar-web/src/org/traccar/web/server/model/DataServiceImpl.java would be great.

**Comment by tananaev** [comment]
I don't like Hibernate library. It's too heavy and it doesn't generate optimal SQL queries.

**Comment by c4oe** [comment]
What about using Cesium (cesiumjs.org) and Geoserver (http://geoserver.org/)?

**Comment by tananaev** [comment]
Can you give some more details on those libraries and how they can be useful in Traccar web interface?

**Comment by c4oe** [comment]
Even better. Let's Skype, and I'll show you a demo.

**Comment by c4oe** [comment]
Skype ID: cameron.hunt.tra

**Comment by tananaev** [comment]
Sorry, I cannot skype at the moment.

**Comment by c4oe** [comment]
Take a look at this demo: http://cesiumjs.org/demos/doarama.html. This should give you an idea of some of things that are possible with GPS visualization.

**Comment by tananaev** [comment]
That looks nice, but I think in most cases people want to see regular flat map like Google Maps. Also documentation is quite poor and I can't even find where the map data is coming from.

**Comment by c4oe** [comment]
The map can switch between 3d, 2.5 D, and 2D views. Map data can come from any public server (e.g., OpenStreetMap) or your own system (like Geoserver).

**Comment by tananaev** [comment]
I selected OpenLayers because it has a lot of examples and documentation on the Internet. Why do you think Cesium is better?

**Comment by gabrielcz** [comment]
keep it simple. simple is better. normal maps.

2015-03-02 17:46 GMT-03:00 Anton Tananaev <notifications@github.com>:

> I selected OpenLayers because it has a lot of examples and documentation
> on the Internet. Why do you think Cesium is better?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tananaev/traccar-web/issues/251#issuecomment-76817024>
> .
>



-- 
.::.gabrielcz.::.

**Comment by c4oe** [comment]
I think simple and normal maps are fine, and should be the default. I don't think Cesium is better - per se - but does give you some power: 
a. Out-of-the-box time capabilities: Play history forward or backward at the speed you desire.
b. Ability to show topography (might be useful if the GPS track is going through mountains, or other elevation changes)
c. Ability to show airborne GPS tracks.
d. Ability to assign different 3D models to your tracks (probably overkill).
e. Its usage is growing (the Australian National Map is based on Cesium: nationalmap.nicta.com.au).
f. There has been an OpenLayers/Cesium integration: http://openlayers.org/ol3-cesium/

I just wanted you to be aware of it. It might be complete overkill and/or inappropriate for what you are trying to do.

**Comment by tananaev** [comment]
Thanks. It's definitely good to know all available options, but for now I think I will stick with OpenLayers.

**Comment by gabrielcz** [comment]
we love to have a new interface soon....
are we soon?  ;)

Regards,
GCZ


2015-03-02 18:02 GMT-03:00 Anton Tananaev <notifications@github.com>:

> Thanks. It's definitely good to know all available options, but for now I
> think I will stick with OpenLayers.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tananaev/traccar-web/issues/251#issuecomment-76821798>
> .
>



-- 
.::.gabrielcz.::.

**Comment by tananaev** [comment]
Can't give any estimates, but hopefully soon enough.

**Comment by gabrielcz** [comment]
It's fine! We can wait ! :)

El lunes, 2 de marzo de 2015, Anton Tananaev <notifications@github.com>
escribió:

> Can't give any estimates, but hopefully soon enough.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tananaev/traccar-web/issues/251#issuecomment-76863252>
> .
>


-- 
.::.gabrielcz.::.

**Comment by iuricmp** [comment]
I would like to know If a pure js/html interface interest you guys? I mean angular + bootstrap. I'm planning to do a web interface (opensource of course) and I want to listen you first. Opinions and thoughts are welcome.

**Comment by Jeferex** [comment]
From the README:

# ~~Traccar Web Interface~~

Repository is **DEPRECATED**. It contains **old** Traccar web interface (GWT-based). New web interface can be found here:

* [**New Traccar Web Interface**](https://github.com/tananaev/traccar/tree/master/web)

For any issues related to Traccar server or web interface please use main issue tracker:

* [**Traccar Issue Tracker**](https://github.com/tananaev/traccar/issues)

**Comment by Jeferex** [comment]
@iuricmp If you can do it, just do it. I think it would be great to have many options where to choose from. Thanks

**Comment by tananaev** [comment]
@iuricmp, Traccar already has pure JavaScript web interface, but you are free to implement another one if you want.
