### ISSUE TITLE
Reset user password

### ISSUE THREAD

**Issue by ramondeklein** [tananaev/traccar-web#252]
I still have the administrator, but a user forgot his password. How can I reset the password?

**Comment by vitalidze** [comment]
You can update it only by running query to the database, something like:

````sql
UPDATE users SET password='new_password' WHERE login='username'
````

[My mod](http://traccar.litvak.su) has an UI menu to reset password for another user, which is available for 'administrator' or 'manager' user.

**Comment by ramondeklein** [comment]
Would be a nice feature, that administrators can set other user's passwords. How can I enter commands directly on the database (I am using the H2 engine).

BTW: It's bad practice to store the plain-text password. For my Raspberry Pi solution it's no big deal, but might be

**Comment by vitalidze** [comment]
First of all you should stop your running traccar server. Then start [h2 console](http://www.h2database.com/html/quickstart.html#h2_console)

    java -jar lib/h2-{h2-version}.jar

Then per documentation it will run a web UI on 8082 port. Connect using `sa` user and empty password.

P.S. as I said [my fork](http://traccar.litvak.su) already has ability to reset another user's password. Also it has ability to change a way how passwords are stored in database (PLAIN, MD5 or SHA1 sums).

**Comment by mehdisn65** [comment]
Hello dear Anton
What is the type of hachedpassword in H2 database?
MD5 or what?

**Comment by tananaev** [comment]
It's [PBKDF2](https://en.wikipedia.org/wiki/PBKDF2). For parameters see [Hashing class](https://github.com/tananaev/traccar/blob/master/src/org/traccar/helper/Hashing.java).

**Comment by mehdisn65** [comment]
Dear
What is the function that i can access to password field?

**Comment by tananaev** [comment]
You can't access original non-hashed password.

**Comment by mehdisn65** [comment]
I wamt to extract data base to excel to keep the user password safe and making backup.
And need to clear the cache.
And want to change database from H2 too MySQL, is it possible?

**Comment by tananaev** [comment]
Traccar only stores password hash, not the actual password.

It is possible to use MySQL:

https://www.traccar.org/mysql/

If you have any more questions, please create a new issue.

**Comment by mehdisn65** [comment]
Ok, thanks
