### ISSUE TITLE
Can I add the Alarm field to the Archive view in the web?

### ISSUE THREAD

**Issue by RoyTH** [tananaev/traccar-web#254]
In the state view I can see the alarm condition that may have caused the track to be called but this is only for the last track recorded, is it possible to configure this to show in the archive view? if so how do i do this?

Thank you

Roy

**Comment by tananaev** [comment]
No, unfortunately it is not supported in current version.

**Comment by tananaev** [comment]
Alarm and all other additional fields are available in state panel when you click on an archive item.
