### ISSUE TITLE
Geocoder address Cyrillic error encoding

### ISSUE THREAD

**Issue by gyrox** [tananaev/traccar-web#256]
Hello,I'm using the new web interface,but the geocoder address does not go correctly.I use Mysql utf 8.
I live in Bulgaria and Cyrillic is not read.Wath to go?I use ready installation for windows

Best regards

![screenshot studio capture 035](https://cloud.githubusercontent.com/assets/11191642/6369310/b78d12b8-bced-11e4-814c-78091b63af22.png)

**Comment by vitalidze** [comment]
Please post your issue to the project's [issue tracker](https://github.com/vitalidze/traccar-web/issues). 

I will need you to check that database contains valid value and then provide it to me for testing.
