### ISSUE TITLE
Exception while dispatching incoming RPC call

### ISSUE THREAD

**Issue by leifnel** [tananaev/traccar-web#257]
Newest traccar-linux-32-2.11.zip

It seems to be running fine, still I see this in the wrapper.log
Mysql database.

<pre>INFO   | jvm 1    | 2015/03/02 22:46:57 | 2015-03-02 22:46:57.741:WARN:/:Exception while dispatching incoming RPC call
INFO   | jvm 1    | 2015/03/02 22:46:57 | com.google.gwt.user.server.rpc.UnexpectedException: Service method 'public abstract java.util.List org.traccar.web.client.model.DataService.getLatestPositi
ons()' threw an unexpected exception: java.lang.IllegalStateException
INFO   | jvm 1    | 2015/03/02 22:46:57 |       at com.google.gwt.user.server.rpc.RPC.encodeResponseForFailure(RPC.java:389)
INFO   | jvm 1    | 2015/03/02 22:46:57 |       at com.google.gwt.user.server.rpc.RPC.invokeAndEncodeResponse(RPC.java:579)
INFO   | jvm 1    | 2015/03/02 22:46:57 |       at com.google.gwt.user.server.rpc.RemoteServiceServlet.processCall(RemoteServiceServlet.java:265)
INFO   | jvm 1    | 2015/03/02 22:46:57 |       at com.google.gwt.user.server.rpc.RemoteServiceServlet.processPost(RemoteServiceServlet.java:305)
INFO   | jvm 1    | 2015/03/02 22:46:57 |       at com.google.gwt.user.server.rpc.AbstractRemoteServiceServlet.doPost(AbstractRemoteServiceServlet.java:62)
INFO   | jvm 1    | 2015/03/02 22:46:57 |       at javax.servlet.http.HttpServlet.service(HttpServlet.java:688)
INFO   | jvm 1    | 2015/03/02 22:46:57 |       at javax.servlet.http.HttpServlet.service(HttpServlet.java:770)
INFO   | jvm 1    | 2015/03/02 22:46:57 |       at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:684)
INFO   | jvm 1    | 2015/03/02 22:46:57 |       at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:503)
INFO   | jvm 1    | 2015/03/02 22:46:57 |       at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:137)
INFO   | jvm 1    | 2015/03/02 22:46:57 |       at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:557)
INFO   | jvm 1    | 2015/03/02 22:46:57 |       at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:231)
INFO   | jvm 1    | 2015/03/02 22:46:57 |       at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1086)
INFO   | jvm 1    | 2015/03/02 22:46:57 |       at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:429)
INFO   | jvm 1    | 2015/03/02 22:46:57 |       at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:193)
INFO   | jvm 1    | 2015/03/02 22:46:57 |       at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1020)
INFO   | jvm 1    | 2015/03/02 22:46:57 |       at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:135)
INFO   | jvm 1    | 2015/03/02 22:46:57 |       at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116)
INFO   | jvm 1    | 2015/03/02 22:46:57 |       at org.eclipse.jetty.server.Server.handle(Server.java:370)
INFO   | jvm 1    | 2015/03/02 22:46:57 |       at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:494)
INFO   | jvm 1    | 2015/03/02 22:46:57 |       at org.eclipse.jetty.server.AbstractHttpConnection.content(AbstractHttpConnection.java:982)
INFO   | jvm 1    | 2015/03/02 22:46:57 |       at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.content(AbstractHttpConnection.java:1043)
INFO   | jvm 1    | 2015/03/02 22:46:57 |       at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:865)
INFO   | jvm 1    | 2015/03/02 22:46:57 |       at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:240)
INFO   | jvm 1    | 2015/03/02 22:46:57 |       at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:82)
INFO   | jvm 1    | 2015/03/02 22:46:57 |       at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:696)
INFO   | jvm 1    | 2015/03/02 22:46:57 |       at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:53)
INFO   | jvm 1    | 2015/03/02 22:46:57 |       at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:608)
INFO   | jvm 1    | 2015/03/02 22:46:57 |       at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:543)
INFO   | jvm 1    | 2015/03/02 22:46:57 |       at java.lang.Thread.run(Thread.java:745)
INFO   | jvm 1    | 2015/03/02 22:46:57 | Caused by:
INFO   | jvm 1    | 2015/03/02 22:46:57 | java.lang.IllegalStateException
INFO   | jvm 1    | 2015/03/02 22:46:57 |       at org.traccar.web.server.model.DataServiceImpl.getSessionUser(DataServiceImpl.java:113)
INFO   | jvm 1    | 2015/03/02 22:46:57 |       at org.traccar.web.server.model.DataServiceImpl.getLatestPositions(DataServiceImpl.java:403)
INFO   | jvm 1    | 2015/03/02 22:46:57 |       at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
INFO   | jvm 1    | 2015/03/02 22:46:57 |       at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
INFO   | jvm 1    | 2015/03/02 22:46:57 |       at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
INFO   | jvm 1    | 2015/03/02 22:46:57 |       at java.lang.reflect.Method.invoke(Method.java:606)
INFO   | jvm 1    | 2015/03/02 22:46:57 |       at com.google.gwt.user.server.rpc.RPC.invokeAndEncodeResponse(RPC.java:561)
INFO   | jvm 1    | 2015/03/02 22:46:57 |       at com.google.gwt.user.server.rpc.RemoteServiceServlet.processCall(RemoteServiceServlet.java:265)
INFO   | jvm 1    | 2015/03/02 22:46:57 |       at com.google.gwt.user.server.rpc.RemoteServiceServlet.processPost(RemoteServiceServlet.java:305)
INFO   | jvm 1    | 2015/03/02 22:46:57 |       at com.google.gwt.user.server.rpc.AbstractRemoteServiceServlet.doPost(AbstractRemoteServiceServlet.java:62)
INFO   | jvm 1    | 2015/03/02 22:46:57 |       at javax.servlet.http.HttpServlet.service(HttpServlet.java:688)
INFO   | jvm 1    | 2015/03/02 22:46:57 |       at javax.servlet.http.HttpServlet.service(HttpServlet.java:770)
INFO   | jvm 1    | 2015/03/02 22:46:57 |       at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:684)
INFO   | jvm 1    | 2015/03/02 22:46:57 |       at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:503)
INFO   | jvm 1    | 2015/03/02 22:46:57 |       at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:137)
INFO   | jvm 1    | 2015/03/02 22:46:57 |       at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:557)
INFO   | jvm 1    | 2015/03/02 22:46:57 |       at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:231)
INFO   | jvm 1    | 2015/03/02 22:46:57 |       at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1086)
INFO   | jvm 1    | 2015/03/02 22:46:57 |       at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:429)
INFO   | jvm 1    | 2015/03/02 22:46:57 |       at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:193)
INFO   | jvm 1    | 2015/03/02 22:46:57 |       at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1020)
INFO   | jvm 1    | 2015/03/02 22:46:57 |       at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:135)
INFO   | jvm 1    | 2015/03/02 22:46:57 |       at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116)
INFO   | jvm 1    | 2015/03/02 22:46:57 |       at org.eclipse.jetty.server.Server.handle(Server.java:370)
INFO   | jvm 1    | 2015/03/02 22:46:57 |       at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:494)
INFO   | jvm 1    | 2015/03/02 22:46:57 |       at org.eclipse.jetty.server.AbstractHttpConnection.content(AbstractHttpConnection.java:982)
INFO   | jvm 1    | 2015/03/02 22:46:57 |       at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.content(AbstractHttpConnection.java:1043)
INFO   | jvm 1    | 2015/03/02 22:46:57 |       at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:865)
INFO   | jvm 1    | 2015/03/02 22:46:57 |       at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:240)
INFO   | jvm 1    | 2015/03/02 22:46:57 |       at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:82)
INFO   | jvm 1    | 2015/03/02 22:46:57 |       at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:696)
INFO   | jvm 1    | 2015/03/02 22:46:57 |       at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:53)
INFO   | jvm 1    | 2015/03/02 22:46:57 |       at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:608)
INFO   | jvm 1    | 2015/03/02 22:46:57 |       at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:543)
INFO   | jvm 1    | 2015/03/02 22:46:57 |       at java.lang.Thread.run(Thread.java:745)</pre>

**Comment by tananaev** [comment]
It means that user is not logged in. Are you using standard Traccar without any modifications? What browser are you using? How do you open web interface (no iFrames?)?

**Comment by leifnel** [comment]
Embarassing... I really wasn't using mysql, perhaps after upgrading, the configfile was overwritten, so it was using the default (h2?) database.

It seems fine now.:-)
