### ISSUE TITLE
Addition of a REST api

### ISSUE THREAD

**Issue by Hemendrajain** [tananaev/traccar-web#258]
Hi Tananaev,
   I want to add a REST api, say 'getData'.

I have added the corresponding function details under:

DataService.java
DataServiceAsync.java
DataServiceImpl.java

I do not know what kind of event does it generate such that the same can be invoked under 'SettingsController.java'

What can I do to invoke the same...

**Comment by gabrielcz** [comment]
I was reading https://www.traccar.org/docs/opengts.jsp and I have a question,
I need to add these lines to common.conf of gts or where I need to create this file or add the lines?
Can anyone try to help with it?

This integration, uses opengts front end, and read from tracer database the data?
I can use the traccar listen device, and use opengts front end ? is this correct?


---
Gabriel Czerniecki
gabrielcz@gmail.com

**Comment by tananaev** [comment]
@Hemendrajain, web interface uses GWT RPC which is not a REST interface.

@gabrielcz, your question is not related to the issue, so please create a separate thread of find a relevant one.

**Comment by tananaev** [comment]
New versions of Traccar include API:

https://www.traccar.org/traccar-api/
