### ISSUE TITLE
Anyone Can help me in settingup web based tracking

### ISSUE THREAD

**Issue by farooqazam** [tananaev/traccar-web#259]
i have installed traccar on my local pc. and client app on my android phone but my phone is not connecting with laptop.

anyone please guide and also let me know if i register a domain name and get hosting what type of hosting i need for starting a free web based gps tracking.

waiting for response faster
my email is farookazam@gmail.com
watsapp is 92-321-8521742

**Comment by tananaev** [comment]
You need a VPS hosting or dedicated server.

**Comment by farooqazam** [comment]
Thanks  Tananaev

can we do chat if you have some time my skype is farookazam. I am planing to start free gpstracking platform.

My Viber / Watsapp +92-321-8521742

**Comment by tananaev** [comment]
Please email me (address in profile) if you still need some help.
