### ISSUE TITLE
I want to change its look and feel?

### ISSUE THREAD

**Issue by umeshbichukale** [tananaev/traccar-web#261]
i want to change look and feel.and want to remove gwt and and by using jsp, javascript, css.Can i change it simply or it is difficult to change look and feel.
Thanks .

**Comment by tananaev** [comment]
It sounds like you want to completely rewrite the web interface.

**Comment by tananaev** [comment]
New web interface uses ExtJS framework. You can read more about themes for it here:

https://docs.sencha.com/extjs/6.0/core_concepts/theming.html
