### ISSUE TITLE
Different information between speed and Mysql

### ISSUE THREAD

**Issue by Mikelord2** [tananaev/traccar-web#263]
Because it may be that the speed shown on the map is different than that stored in mysql, I attached photos of data at the same hour minute second.

![traccar](https://cloud.githubusercontent.com/assets/10438858/7187003/1a34dcc0-e444-11e4-9fa2-d6fb09277eab.JPG)

![traccar2](https://cloud.githubusercontent.com/assets/10438858/7187006/202404b2-e444-11e4-926e-d182c603379e.JPG)

greetings from Chile

**Comment by vitalidze** [comment]
Speed in database is stored in knots, while in your web UI you are using kilometer per hour, 1km = 0.539956803 knots, so 90km = 48.5961123 knots.

**Comment by Mikelord2** [comment]
There will be some form of storage in KMH in the database?

**Comment by vitalidze** [comment]
I don't think so. What's wrong with knots?

**Comment by Mikelord2** [comment]
No really, it's just from the database send some of this data to other servers.

**Comment by Mikelord2** [comment]
Thank you very much for your help!

**Comment by Jeferex** [comment]
Si quieres guardar km/h, modifica la consulta para insertar en traccar.cfg y multiplica la velocidad por 1.852.

Saludos
