### ISSUE TITLE
Web interface down after inactivity

### ISSUE THREAD

**Issue by ekaftan** [tananaev/traccar-web#264]
Hi,

 I have a small server with only me as a user. If I dont use the web interface in about 12 hours it goes down. If I am already logged on I can't get data (fails with a RPC error message) and if I am not logged in every attempt to log in says 'user or password incorrect'.

 From wrapper log I think that the connection to mysql gets closed and that its not detected and the connection not re-opened. GPSs (I have two) still log data to the database. Its just the web interface that goes down

 Am I doing something wrong?

Thanks.

 wrapper.log show this:

<pre>INFO   | jvm 1    | 2015/05/05 09:23:00 | 2015-05-05 09:23:00.791:WARN:/:Exception while dispatching incoming RPC call
INFO   | jvm 1    | 2015/05/05 09:23:00 | com.google.gwt.user.server.rpc.UnexpectedException: Service method 'public abstract org.traccar.web.shared.model.User org.traccar.web.client.model.DataService.login(java.lang.String,java.lang.String)' threw an unexpected exception: javax.persistence.PersistenceException: org.hibernate.exception.JDBCConnectionException: No operations allowed after connection closed.
INFO   | jvm 1    | 2015/05/05 09:23:00 | 	at com.google.gwt.user.server.rpc.RPC.encodeResponseForFailure(RPC.java:389)
INFO   | jvm 1    | 2015/05/05 09:23:00 | 	at com.google.gwt.user.server.rpc.RPC.invokeAndEncodeResponse(RPC.java:579)
INFO   | jvm 1    | 2015/05/05 09:23:00 | 	at com.google.gwt.user.server.rpc.RemoteServiceServlet.processCall(RemoteServiceServlet.java:265)
INFO   | jvm 1    | 2015/05/05 09:23:00 | 	at com.google.gwt.user.server.rpc.RemoteServiceServlet.processPost(RemoteServiceServlet.java:305)
INFO   | jvm 1    | 2015/05/05 09:23:00 | 	at com.google.gwt.user.server.rpc.AbstractRemoteServiceServlet.doPost(AbstractRemoteServiceServlet.java:62)
INFO   | jvm 1    | 2015/05/05 09:23:00 | 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:755)
INFO   | jvm 1    | 2015/05/05 09:23:00 | 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:848)
INFO   | jvm 1    | 2015/05/05 09:23:00 | 	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:684)
INFO   | jvm 1    | 2015/05/05 09:23:00 | 	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:503)
INFO   | jvm 1    | 2015/05/05 09:23:00 | 	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:137)
INFO   | jvm 1    | 2015/05/05 09:23:00 | 	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:557)
INFO   | jvm 1    | 2015/05/05 09:23:00 | 	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:231)
INFO   | jvm 1    | 2015/05/05 09:23:00 | 	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1086)
INFO   | jvm 1    | 2015/05/05 09:23:00 | 	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:429)
INFO   | jvm 1    | 2015/05/05 09:23:00 | 	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:193)
INFO   | jvm 1    | 2015/05/05 09:23:00 | 	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1020)
INFO   | jvm 1    | 2015/05/05 09:23:00 | 	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:135)
INFO   | jvm 1    | 2015/05/05 09:23:00 | 	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116)
INFO   | jvm 1    | 2015/05/05 09:23:00 | 	at org.eclipse.jetty.server.Server.handle(Server.java:370)
INFO   | jvm 1    | 2015/05/05 09:23:00 | 	at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:494)
INFO   | jvm 1    | 2015/05/05 09:23:00 | 	at org.eclipse.jetty.server.AbstractHttpConnection.content(AbstractHttpConnection.java:982)
INFO   | jvm 1    | 2015/05/05 09:23:00 | 	at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.content(AbstractHttpConnection.java:1043)
INFO   | jvm 1    | 2015/05/05 09:23:00 | 	at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:865)
INFO   | jvm 1    | 2015/05/05 09:23:00 | 	at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:240)
INFO   | jvm 1    | 2015/05/05 09:23:00 | 	at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:82)
INFO   | jvm 1    | 2015/05/05 09:23:00 | 	at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:696)
INFO   | jvm 1    | 2015/05/05 09:23:00 | 	at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:53)
INFO   | jvm 1    | 2015/05/05 09:23:00 | 	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:608)
INFO   | jvm 1    | 2015/05/05 09:23:00 | 	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:543)
INFO   | jvm 1    | 2015/05/05 09:23:00 | 	at java.lang.Thread.run(Thread.java:701)
INFO   | jvm 1    | 2015/05/05 09:23:00 | Caused by: 
INFO   | jvm 1    | 2015/05/05 09:23:00 | javax.persistence.PersistenceException: org.hibernate.exception.JDBCConnectionException: No operations allowed after connection closed.
INFO   | jvm 1    | 2015/05/05 09:23:00 | 	at org.hibernate.ejb.AbstractEntityManagerImpl.convert(AbstractEntityManagerImpl.java:1387)
INFO   | jvm 1    | 2015/05/05 09:23:00 | 	at org.hibernate.ejb.AbstractEntityManagerImpl.convert(AbstractEntityManagerImpl.java:1310)
INFO   | jvm 1    | 2015/05/05 09:23:00 | 	at org.hibernate.ejb.QueryImpl.getResultList(QueryImpl.java:273)
INFO   | jvm 1    | 2015/05/05 09:23:00 | 	at org.traccar.web.server.model.DataServiceImpl.login(DataServiceImpl.java:130)
INFO   | jvm 1    | 2015/05/05 09:23:00 | 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
INFO   | jvm 1    | 2015/05/05 09:23:00 | 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
INFO   | jvm 1    | 2015/05/05 09:23:00 | 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
INFO   | jvm 1    | 2015/05/05 09:23:00 | 	at java.lang.reflect.Method.invoke(Method.java:622)
INFO   | jvm 1    | 2015/05/05 09:23:00 | 	at com.google.gwt.user.server.rpc.RPC.invokeAndEncodeResponse(RPC.java:561)
INFO   | jvm 1    | 2015/05/05 09:23:00 | 	at com.google.gwt.user.server.rpc.RemoteServiceServlet.processCall(RemoteServiceServlet.java:265)
INFO   | jvm 1    | 2015/05/05 09:23:00 | 	at com.google.gwt.user.server.rpc.RemoteServiceServlet.processPost(RemoteServiceServlet.java:305)
INFO   | jvm 1    | 2015/05/05 09:23:00 | 	at com.google.gwt.user.server.rpc.AbstractRemoteServiceServlet.doPost(AbstractRemoteServiceServlet.java:62)
INFO   | jvm 1    | 2015/05/05 09:23:00 | 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:755)
INFO   | jvm 1    | 2015/05/05 09:23:00 | 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:848)
INFO   | jvm 1    | 2015/05/05 09:23:00 | 	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:684)
INFO   | jvm 1    | 2015/05/05 09:23:00 | 	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:503)
INFO   | jvm 1    | 2015/05/05 09:23:00 | 	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:137)
INFO   | jvm 1    | 2015/05/05 09:23:00 | 	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:557)
INFO   | jvm 1    | 2015/05/05 09:23:00 | 	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:231)
INFO   | jvm 1    | 2015/05/05 09:23:00 | 	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1086)
INFO   | jvm 1    | 2015/05/05 09:23:00 | 	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:429)
INFO   | jvm 1    | 2015/05/05 09:23:00 | 	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:193)
INFO   | jvm 1    | 2015/05/05 09:23:00 | 	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1020)
INFO   | jvm 1    | 2015/05/05 09:23:00 | 	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:135)
INFO   | jvm 1    | 2015/05/05 09:23:00 | 	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116)
INFO   | jvm 1    | 2015/05/05 09:23:00 | 	at org.eclipse.jetty.server.Server.handle(Server.java:370)
INFO   | jvm 1    | 2015/05/05 09:23:00 | 	at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:494)
INFO   | jvm 1    | 2015/05/05 09:23:00 | 	at org.eclipse.jetty.server.AbstractHttpConnection.content(AbstractHttpConnection.java:982)
INFO   | jvm 1    | 2015/05/05 09:23:00 | 	at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.content(AbstractHttpConnection.java:1043)
INFO   | jvm 1    | 2015/05/05 09:23:00 | 	at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:865)
INFO   | jvm 1    | 2015/05/05 09:23:00 | 	at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:240)
INFO   | jvm 1    | 2015/05/05 09:23:00 | 	at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:82)
INFO   | jvm 1    | 2015/05/05 09:23:00 | 	at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:696)
INFO   | jvm 1    | 2015/05/05 09:23:00 | 	at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:53)
INFO   | jvm 1    | 2015/05/05 09:23:00 | 	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:608)
INFO   | jvm 1    | 2015/05/05 09:23:00 | 	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:543)
INFO   | jvm 1    | 2015/05/05 09:23:00 | 	at java.lang.Thread.run(Thread.java:701)
INFO   | jvm 1    | 2015/05/05 09:23:00 | Caused by: 
INFO   | jvm 1    | 2015/05/05 09:23:00 | org.hibernate.exception.JDBCConnectionException: No operations allowed after connection closed.
INFO   | jvm 1    | 2015/05/05 09:23:00 | 	at org.hibernate.exception.internal.SQLExceptionTypeDelegate.convert(SQLExceptionTypeDelegate.java:67)
INFO   | jvm 1    | 2015/05/05 09:23:00 | 	at org.hibernate.exception.internal.StandardSQLExceptionConverter.convert(StandardSQLExceptionConverter.java:49)
INFO   | jvm 1    | 2015/05/05 09:23:00 | 	at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:125)
INFO   | jvm 1    | 2015/05/05 09:23:00 | 	at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:110)
INFO   | jvm 1    | 2015/05/05 09:23:00 | 	at org.hibernate.engine.jdbc.internal.proxy.ConnectionProxyHandler.continueInvocation(ConnectionProxyHandler.java:146)
INFO   | jvm 1    | 2015/05/05 09:23:00 | 	at org.hibernate.engine.jdbc.internal.proxy.AbstractProxyHandler.invoke(AbstractProxyHandler.java:81)
INFO   | jvm 1    | 2015/05/05 09:23:00 | 	at com.sun.proxy.$Proxy16.prepareStatement(Unknown Source)
INFO   | jvm 1    | 2015/05/05 09:23:00 | 	at org.hibernate.engine.jdbc.internal.StatementPreparerImpl$5.doPrepare(StatementPreparerImpl.java:147)
INFO   | jvm 1    | 2015/05/05 09:23:00 | 	at org.hibernate.engine.jdbc.internal.StatementPreparerImpl$StatementPreparationTemplate.prepareStatement(StatementPreparerImpl.java:166)
INFO   | jvm 1    | 2015/05/05 09:23:00 | 	at org.hibernate.engine.jdbc.internal.StatementPreparerImpl.prepareQueryStatement(StatementPreparerImpl.java:145)
INFO   | jvm 1    | 2015/05/05 09:23:00 | 	at org.hibernate.loader.Loader.prepareQueryStatement(Loader.java:1854)
INFO   | jvm 1    | 2015/05/05 09:23:00 | 	at org.hibernate.loader.Loader.executeQueryStatement(Loader.java:1831)
INFO   | jvm 1    | 2015/05/05 09:23:00 | 	at org.hibernate.loader.Loader.executeQueryStatement(Loader.java:1811)
INFO   | jvm 1    | 2015/05/05 09:23:00 | 	at org.hibernate.loader.Loader.doQuery(Loader.java:899)
INFO   | jvm 1    | 2015/05/05 09:23:00 | 	at org.hibernate.loader.Loader.doQueryAndInitializeNonLazyCollections(Loader.java:341)
INFO   | jvm 1    | 2015/05/05 09:23:00 | 	at org.hibernate.loader.Loader.doList(Loader.java:2516)
INFO   | jvm 1    | 2015/05/05 09:23:00 | 	at org.hibernate.loader.Loader.doList(Loader.java:2502)
INFO   | jvm 1    | 2015/05/05 09:23:00 | 	at org.hibernate.loader.Loader.listIgnoreQueryCache(Loader.java:2332)
INFO   | jvm 1    | 2015/05/05 09:23:00 | 	at org.hibernate.loader.Loader.list(Loader.java:2327)
INFO   | jvm 1    | 2015/05/05 09:23:00 | 	at org.hibernate.loader.hql.QueryLoader.list(QueryLoader.java:490)
INFO   | jvm 1    | 2015/05/05 09:23:00 | 	at org.hibernate.hql.internal.ast.QueryTranslatorImpl.list(QueryTranslatorImpl.java:355)
INFO   | jvm 1    | 2015/05/05 09:23:00 | 	at org.hibernate.engine.query.spi.HQLQueryPlan.performList(HQLQueryPlan.java:195)
INFO   | jvm 1    | 2015/05/05 09:23:00 | 	at org.hibernate.internal.SessionImpl.list(SessionImpl.java:1247)
INFO   | jvm 1    | 2015/05/05 09:23:00 | 	at org.hibernate.internal.QueryImpl.list(QueryImpl.java:101)
INFO   | jvm 1    | 2015/05/05 09:23:00 | 	at org.hibernate.ejb.QueryImpl.getResultList(QueryImpl.java:264)
INFO   | jvm 1    | 2015/05/05 09:23:00 | 	at org.traccar.web.server.model.DataServiceImpl.login(DataServiceImpl.java:130)
INFO   | jvm 1    | 2015/05/05 09:23:00 | 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
INFO   | jvm 1    | 2015/05/05 09:23:00 | 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
INFO   | jvm 1    | 2015/05/05 09:23:00 | 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
INFO   | jvm 1    | 2015/05/05 09:23:00 | 	at java.lang.reflect.Method.invoke(Method.java:622)
INFO   | jvm 1    | 2015/05/05 09:23:00 | 	at com.google.gwt.user.server.rpc.RPC.invokeAndEncodeResponse(RPC.java:561)
INFO   | jvm 1    | 2015/05/05 09:23:00 | 	at com.google.gwt.user.server.rpc.RemoteServiceServlet.processCall(RemoteServiceServlet.java:265)
INFO   | jvm 1    | 2015/05/05 09:23:00 | 	at com.google.gwt.user.server.rpc.RemoteServiceServlet.processPost(RemoteServiceServlet.java:305)
INFO   | jvm 1    | 2015/05/05 09:23:00 | 	at com.google.gwt.user.server.rpc.AbstractRemoteServiceServlet.doPost(AbstractRemoteServiceServlet.java:62)
INFO   | jvm 1    | 2015/05/05 09:23:00 | 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:755)
INFO   | jvm 1    | 2015/05/05 09:23:00 | 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:848)
INFO   | jvm 1    | 2015/05/05 09:23:00 | 	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:684)
INFO   | jvm 1    | 2015/05/05 09:23:00 | 	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:503)
INFO   | jvm 1    | 2015/05/05 09:23:00 | 	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:137)
INFO   | jvm 1    | 2015/05/05 09:23:00 | 	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:557)
INFO   | jvm 1    | 2015/05/05 09:23:00 | 	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:231)
INFO   | jvm 1    | 2015/05/05 09:23:00 | 	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1086)
INFO   | jvm 1    | 2015/05/05 09:23:00 | 	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:429)
INFO   | jvm 1    | 2015/05/05 09:23:00 | 	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:193)
INFO   | jvm 1    | 2015/05/05 09:23:00 | 	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1020)
INFO   | jvm 1    | 2015/05/05 09:23:00 | 	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:135)
INFO   | jvm 1    | 2015/05/05 09:23:00 | 	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116)
INFO   | jvm 1    | 2015/05/05 09:23:00 | 	at org.eclipse.jetty.server.Server.handle(Server.java:370)
INFO   | jvm 1    | 2015/05/05 09:23:00 | 	at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:494)
INFO   | jvm 1    | 2015/05/05 09:23:00 | 	at org.eclipse.jetty.server.AbstractHttpConnection.content(AbstractHttpConnection.java:982)
INFO   | jvm 1    | 2015/05/05 09:23:00 | 	at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.content(AbstractHttpConnection.java:1043)
INFO   | jvm 1    | 2015/05/05 09:23:00 | 	at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:865)
INFO   | jvm 1    | 2015/05/05 09:23:00 | 	at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:240)
INFO   | jvm 1    | 2015/05/05 09:23:00 | 	at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:82)
INFO   | jvm 1    | 2015/05/05 09:23:00 | 	at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:696)
INFO   | jvm 1    | 2015/05/05 09:23:00 | 	at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:53)
INFO   | jvm 1    | 2015/05/05 09:23:00 | 	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:608)
INFO   | jvm 1    | 2015/05/05 09:23:00 | 	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:543)
INFO   | jvm 1    | 2015/05/05 09:23:00 | 	at java.lang.Thread.run(Thread.java:701)
INFO   | jvm 1    | 2015/05/05 09:23:00 | Caused by: 
INFO   | jvm 1    | 2015/05/05 09:23:00 | com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: No operations allowed after connection closed.
INFO   | jvm 1    | 2015/05/05 09:23:00 | 	at sun.reflect.GeneratedConstructorAccessor25.newInstance(Unknown Source)
INFO   | jvm 1    | 2015/05/05 09:23:00 | 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
INFO   | jvm 1    | 2015/05/05 09:23:00 | 	at java.lang.reflect.Constructor.newInstance(Constructor.java:534)
INFO   | jvm 1    | 2015/05/05 09:23:00 | 	at com.mysql.jdbc.Util.handleNewInstance(Util.java:377)
INFO   | jvm 1    | 2015/05/05 09:23:00 | 	at com.mysql.jdbc.Util.getInstance(Util.java:360)
INFO   | jvm 1    | 2015/05/05 09:23:00 | 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:956)
INFO   | jvm 1    | 2015/05/05 09:23:00 | 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:935)
INFO   | jvm 1    | 2015/05/05 09:23:00 | 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:924)
INFO   | jvm 1    | 2015/05/05 09:23:00 | 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:870)
INFO   | jvm 1    | 2015/05/05 09:23:00 | 	at com.mysql.jdbc.ConnectionImpl.throwConnectionClosedException(ConnectionImpl.java:1232)
INFO   | jvm 1    | 2015/05/05 09:23:00 | 	at com.mysql.jdbc.ConnectionImpl.checkClosed(ConnectionImpl.java:1225)
INFO   | jvm 1    | 2015/05/05 09:23:00 | 	at com.mysql.jdbc.ConnectionImpl.prepareStatement(ConnectionImpl.java:4104)
INFO   | jvm 1    | 2015/05/05 09:23:00 | 	at com.mysql.jdbc.ConnectionImpl.prepareStatement(ConnectionImpl.java:4073)
INFO   | jvm 1    | 2015/05/05 09:23:00 | 	at com.mchange.v2.c3p0.impl.NewProxyConnection.prepareStatement(NewProxyConnection.java:469)
INFO   | jvm 1    | 2015/05/05 09:23:00 | 	at sun.reflect.GeneratedMethodAccessor9.invoke(Unknown Source)
INFO   | jvm 1    | 2015/05/05 09:23:00 | 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
INFO   | jvm 1    | 2015/05/05 09:23:00 | 	at java.lang.reflect.Method.invoke(Method.java:622)
INFO   | jvm 1    | 2015/05/05 09:23:00 | 	at org.hibernate.engine.jdbc.internal.proxy.ConnectionProxyHandler.continueInvocation(ConnectionProxyHandler.java:138)
INFO   | jvm 1    | 2015/05/05 09:23:00 | 	at org.hibernate.engine.jdbc.internal.proxy.AbstractProxyHandler.invoke(AbstractProxyHandler.java:81)
INFO   | jvm 1    | 2015/05/05 09:23:00 | 	at com.sun.proxy.$Proxy16.prepareStatement(Unknown Source)
INFO   | jvm 1    | 2015/05/05 09:23:00 | 	at org.hibernate.engine.jdbc.internal.StatementPreparerImpl$5.doPrepare(StatementPreparerImpl.java:147)
INFO   | jvm 1    | 2015/05/05 09:23:00 | 	at org.hibernate.engine.jdbc.internal.StatementPreparerImpl$StatementPreparationTemplate.prepareStatement(StatementPreparerImpl.java:166)
INFO   | jvm 1    | 2015/05/05 09:23:00 | 	at org.hibernate.engine.jdbc.internal.StatementPreparerImpl.prepareQueryStatement(StatementPreparerImpl.java:145)
INFO   | jvm 1    | 2015/05/05 09:23:00 | 	at org.hibernate.loader.Loader.prepareQueryStatement(Loader.java:1854)
INFO   | jvm 1    | 2015/05/05 09:23:00 | 	at org.hibernate.loader.Loader.executeQueryStatement(Loader.java:1831)
INFO   | jvm 1    | 2015/05/05 09:23:00 | 	at org.hibernate.loader.Loader.executeQueryStatement(Loader.java:1811)
INFO   | jvm 1    | 2015/05/05 09:23:00 | 	at org.hibernate.loader.Loader.doQuery(Loader.java:899)
INFO   | jvm 1    | 2015/05/05 09:23:00 | 	at org.hibernate.loader.Loader.doQueryAndInitializeNonLazyCollections(Loader.java:341)
INFO   | jvm 1    | 2015/05/05 09:23:00 | 	at org.hibernate.loader.Loader.doList(Loader.java:2516)
INFO   | jvm 1    | 2015/05/05 09:23:00 | 	at org.hibernate.loader.Loader.doList(Loader.java:2502)
INFO   | jvm 1    | 2015/05/05 09:23:00 | 	at org.hibernate.loader.Loader.listIgnoreQueryCache(Loader.java:2332)
INFO   | jvm 1    | 2015/05/05 09:23:00 | 	at org.hibernate.loader.Loader.list(Loader.java:2327)
INFO   | jvm 1    | 2015/05/05 09:23:00 | 	at org.hibernate.loader.hql.QueryLoader.list(QueryLoader.java:490)
INFO   | jvm 1    | 2015/05/05 09:23:00 | 	at org.hibernate.hql.internal.ast.QueryTranslatorImpl.list(QueryTranslatorImpl.java:355)
INFO   | jvm 1    | 2015/05/05 09:23:00 | 	at org.hibernate.engine.query.spi.HQLQueryPlan.performList(HQLQueryPlan.java:195)
INFO   | jvm 1    | 2015/05/05 09:23:00 | 	at org.hibernate.internal.SessionImpl.list(SessionImpl.java:1247)
INFO   | jvm 1    | 2015/05/05 09:23:00 | 	at org.hibernate.internal.QueryImpl.list(QueryImpl.java:101)
INFO   | jvm 1    | 2015/05/05 09:23:00 | 	at org.hibernate.ejb.QueryImpl.getResultList(QueryImpl.java:264)
INFO   | jvm 1    | 2015/05/05 09:23:00 | 	at org.traccar.web.server.model.DataServiceImpl.login(DataServiceImpl.java:130)
INFO   | jvm 1    | 2015/05/05 09:23:00 | 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
INFO   | jvm 1    | 2015/05/05 09:23:00 | 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
INFO   | jvm 1    | 2015/05/05 09:23:00 | 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
INFO   | jvm 1    | 2015/05/05 09:23:00 | 	at java.lang.reflect.Method.invoke(Method.java:622)
INFO   | jvm 1    | 2015/05/05 09:23:00 | 	at com.google.gwt.user.server.rpc.RPC.invokeAndEncodeResponse(RPC.java:561)
INFO   | jvm 1    | 2015/05/05 09:23:00 | 	at com.google.gwt.user.server.rpc.RemoteServiceServlet.processCall(RemoteServiceServlet.java:265)
INFO   | jvm 1    | 2015/05/05 09:23:00 | 	at com.google.gwt.user.server.rpc.RemoteServiceServlet.processPost(RemoteServiceServlet.java:305)
INFO   | jvm 1    | 2015/05/05 09:23:00 | 	at com.google.gwt.user.server.rpc.AbstractRemoteServiceServlet.doPost(AbstractRemoteServiceServlet.java:62)
INFO   | jvm 1    | 2015/05/05 09:23:00 | 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:755)
INFO   | jvm 1    | 2015/05/05 09:23:00 | 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:848)
INFO   | jvm 1    | 2015/05/05 09:23:00 | 	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:684)
INFO   | jvm 1    | 2015/05/05 09:23:00 | 	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:503)
INFO   | jvm 1    | 2015/05/05 09:23:00 | 	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:137)
INFO   | jvm 1    | 2015/05/05 09:23:00 | 	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:557)
INFO   | jvm 1    | 2015/05/05 09:23:00 | 	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:231)
INFO   | jvm 1    | 2015/05/05 09:23:00 | 	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1086)
INFO   | jvm 1    | 2015/05/05 09:23:00 | 	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:429)
INFO   | jvm 1    | 2015/05/05 09:23:00 | 	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:193)
INFO   | jvm 1    | 2015/05/05 09:23:00 | 	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1020)
INFO   | jvm 1    | 2015/05/05 09:23:00 | 	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:135)
INFO   | jvm 1    | 2015/05/05 09:23:00 | 	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116)
INFO   | jvm 1    | 2015/05/05 09:23:00 | 	at org.eclipse.jetty.server.Server.handle(Server.java:370)
INFO   | jvm 1    | 2015/05/05 09:23:00 | 	at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:494)
INFO   | jvm 1    | 2015/05/05 09:23:00 | 	at org.eclipse.jetty.server.AbstractHttpConnection.content(AbstractHttpConnection.java:982)
INFO   | jvm 1    | 2015/05/05 09:23:00 | 	at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.content(AbstractHttpConnection.java:1043)
INFO   | jvm 1    | 2015/05/05 09:23:00 | 	at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:865)
INFO   | jvm 1    | 2015/05/05 09:23:00 | 	at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:240)
INFO   | jvm 1    | 2015/05/05 09:23:00 | 	at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:82)
INFO   | jvm 1    | 2015/05/05 09:23:00 | 	at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:696)
INFO   | jvm 1    | 2015/05/05 09:23:00 | 	at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:53)
INFO   | jvm 1    | 2015/05/05 09:23:00 | 	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:608)
INFO   | jvm 1    | 2015/05/05 09:23:00 | 	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:543)
INFO   | jvm 1    | 2015/05/05 09:23:00 | 	at java.lang.Thread.run(Thread.java:701)</pre>

**Comment by vitalidze** [comment]
This is an issue with web application design. It holds long running hibernate session objects attached to the HTTP session. I believe if you clean up cookies or try from another browser the problem will be solved.

**Comment by tananaev** [comment]
Alternatively you can try to change MySQL connection timeout.

**Comment by tananaev** [comment]
Old web interface is obsolete. If new web interface has same/similar issue, please report it here:

https://github.com/tananaev/traccar/issues
