### ISSUE TITLE
Export button not present

### ISSUE THREAD

**Issue by markossx** [tananaev/traccar-web#266]
Hi,
in my install I can't see button Export, only Load button is visible,
please, see screen.
Version 2.12, where I made a mistake, help,
regards, 
Piotr

![export_button](https://cloud.githubusercontent.com/assets/12391256/7560992/b2566efa-f7c8-11e4-9d2e-40bd15529257.gif)

**Comment by vitalidze** [comment]
This is the default version of web UI, which does not have exporting functionality. You need to follow [these instructions](http://traccar.litvak.su/installation.html) to update default version to the enhanced one.

**Comment by markossx** [comment]
Thanks for the tip!
It works fine,

regards,
Piotr

**Comment by renaudallard** [comment]
Is there a plan to add this functionality in the "official" version of traccar?

**Comment by tananaev** [comment]
Yes, there are plans to implement it in official version.

**Comment by tananaev** [comment]
Latest version has CSV export option.
