### ISSUE TITLE
Clean - Optimize

### ISSUE THREAD

**Issue by Mikelord2** [tananaev/traccar-web#267]
Sorry if it is a subject seen before, I searched but found nothing that could help me, I'm using this system and it worked very well, but I notice that the database is gaining weight, how can "optimize" or delete data oldest ?, because I tried deleting (after making a backup), and does not allow clear points marked as old.
Any help is welcome

regards

MCO

**Comment by tananaev** [comment]
On the demo server (which uses MySQL) I use following queries to clear data older than 3 months:
<pre>DELETE FROM positions WHERE time < DATE_ADD(NOW(), INTERVAL -3 MONTH);
UPDATE devices SET latestPosition_id = NULL WHERE latestPosition_id NOT IN (SELECT id FROM positions);</pre>

**Comment by Mikelord2** [comment]
The query returns this error.
" Error
SQL query:
DELETE FROM WHERE TIME positions <DATE_ADD (NOW (), INTERVAL MONTH -3);
MySQL said: Documentation
# 1451 - Can not delete or update a parent row: a foreign key constraint fails (`datatracker`.`events`, events_fkey_position_id`` CONSTRAINT FOREIGN KEY (`position_id`) REFERENCES` positions` (`id`))  "



The oldest position is "2009-12-31 21:00:01" probably mistakenly had some GPS that you will keep in memory that date and informed the server.

**Comment by tananaev** [comment]
Standard Traccar database doesn't have `events` table.

**Comment by vitalidze** [comment]
Looks like you are using my version of the web UI, which contains `events`. I guess you need additional query to clean up events first:

````SQL
DELETE e FROM events e INNER JOIN positions p ON p.id=e.position_id WHERE p.time < DATE_ADD(NOW(), INTERVAL -3 MONTH);
````

So to clean up data you will need three queries (**don't forget to backup database if you have sensitive data**):

````SQL
DELETE e FROM events e INNER JOIN positions p ON p.id=e.position_id WHERE p.time < DATE_ADD(NOW(), INTERVAL -3 MONTH);
DELETE FROM positions WHERE time < DATE_ADD(NOW(), INTERVAL -3 MONTH);
UPDATE devices SET latestPosition_id = NULL WHERE latestPosition_id NOT IN (SELECT id FROM positions);
````

I would also recommend to enclose all three in database transaction.

**Comment by connectnet** [comment]
Im looking for a solution for an automatically deletion every 3 month.
This does not works:
<entry key="database.initialize">
DELETE e FROM events e INNER JOIN positions p ON p.id=e.position_id WHERE p.time < DATE_ADD(NOW(), INTERVAL -3 MONTH);
DELETE FROM positions WHERE time < DATE_ADD(NOW(), INTERVAL -3 MONTH);
UPDATE devices SET latestPosition_id = NULL WHERE latestPosition_id NOT IN (SELECT id FROM positions);
</entry>

**Comment by tananaev** [comment]
What is `database.initialize` parameter?

**Comment by connectnet** [comment]
Please take a look here:
https://github.com/tananaev/traccar/issues/63

**Comment by tananaev** [comment]
It should be possible to clean database records using SQL scripts. It can be automated as well.

**Comment by leontino** [comment]
Dear, what I do for continue only last 3 months of positions and erase the rest?

**Comment by tananaev** [comment]
@leontino, please don't comment on old closed threads.

As for your question, check [config documentation](https://www.traccar.org/configuration-file/).

**Comment by sankalpask** [comment]
Is that query still working? giving this error when I try to execute the query,
#1451 - Cannot delete or update a parent row: a foreign key constraint fails (`track`.`events`, CONSTRAINT `events_fkey_position_id` FOREIGN KEY (`position_id`) REFERENCES `positions` (`id`))

**Comment by tananaev** [comment]
No, it won't work because it's for old version. Commands for 3.x version:
```sql
SET foreign_key_checks = 0;
DELETE FROM events WHERE serverTime < DATE_ADD(NOW(), INTERVAL -3 MONTH);
DELETE FROM positions WHERE serverTime < DATE_ADD(NOW(), INTERVAL -3 MONTH);
UPDATE devices SET positionId = NULL WHERE positionId NOT IN (SELECT id FROM positions);
SET foreign_key_checks = 1;
```
