### ISSUE TITLE
Notification API

### ISSUE THREAD

**Issue by Unr3al2** [tananaev/traccar-web#268]
Hello,
Good work with version 2.12 (17 Apr 2015).
I miss the notification only for API.
It would be possible to send SMS with location.
A sample address: http://addressapi/sms.php?to=0048111111111&text=${messagetext}

How do succeed in SMS notification API, it will need the ability to choose notification.

Regards,
Unr3al2

**Comment by tananaev** [comment]
Traccar doesn't support SMS.

**Comment by Unr3al2** [comment]
Whether it will handle the HTTP protocol?

**Comment by tananaev** [comment]
What do you mean by "it"? There is no notification API.

**Comment by Unr3al2** [comment]
The new version sent email.
It would be cool if launched the http address.
A sample address: http://addressapi/sms.php?to=0048111111111&text=${messagetext}

**Comment by vitalidze** [comment]
@Unr3al2 I think you are talking about my version of web UI. This issue tracker is related with old version, which does not have notifications (and many other functions that exist in my version). So, please don't submit your questions here. There is a separate issue tracker for my mod: https://github.com/vitalidze/traccar-web/issues

Regarding your base request there is already an issue here: https://github.com/vitalidze/traccar-web/issues/153 - I think this is what you are talking about. I have it in plans.

**Comment by Unr3al2** [comment]
Super,
That's what I meant.
I watched topic :)
