### ISSUE TITLE
Archive Column Sorting

### ISSUE THREAD

**Issue by Starsiss** [tananaev/traccar-web#269]
Hello,
I've been noticing that the archive positions grid is randomly sorted by time.the data appear like:
10:30:51
10:29:36
09:56:28
12:33:12
and so on. 
this has happened with firefox 37,explorer 11 and chrome, so I guess it may be some kind of jvm problem? this looks to appear when trying to sort the columns ascending or descending, and clearing the cache sometimes fix it, sometimes, and later, the problem just reappear.

have you been aware of this kind of problem before? I don't think there is anything wrong with the code, but it makes quite difficult to follow the routes of the devices.

thanks,

**Comment by Starsiss** [comment]
I found out that this problem happens when the list of position is larger than the archive view and you need to scroll to be able to see all the position, then is when the positions get messy. If you resize the archive view so all the position fit without scrolling, then they are sorted correctly.

Hope this helps a little.
Thanks,

**Comment by tananaev** [comment]
I suspect this might be some problem in GXT. Anyway, new web interface is very close to completion, so there is no point in fixing the old one.

**Comment by Starsiss** [comment]
Do you have an idea more or less when do you expect to have it finished?

thanks,

**Comment by tananaev** [comment]
I hope to finish it next week or the week after.

**Comment by tananaev** [comment]
New web interface has been available for some time now.
