### ISSUE TITLE
Groups

### ISSUE THREAD

**Issue by cgarbero** [tananaev/traccar-web#271]
Is There a way to create groups for each devices create ?

**Comment by tananaev** [comment]
No, it current version there is no way to group devices. I plan to add this feature in future.

**Comment by cgarbero** [comment]
thanks

**Comment by cgarbero** [comment]
Do u know when are goig to implement?

**Comment by tananaev** [comment]
Not very soon because there are many higher priority features in the backlog.

**Comment by cgarbero** [comment]
how can i make it ? which program can i use for edit and colaborate in the development of traccar? can u give me links for download ? thanks

**Comment by tananaev** [comment]
You need NetBeans (https://netbeans.org/downloads/).

I am working on a new web interface which is almost finished. You can use NetBeans to modify it, but if you want to modify old web interface you need an Eclipse IDE (https://eclipse.org/downloads/) with Google plugin (https://developers.google.com/eclipse/).

**Comment by cgarbero** [comment]
wich version of eclipse do u suggest me

**Comment by tananaev** [comment]
Latest.

**Comment by tananaev** [comment]
It makes sense to implement it in the new web interface instead of the old one.

**Comment by tananaev** [comment]
Groups have been available in Traccar for a while.
