### ISSUE TITLE
for gt06 power is always null? 

### ISSUE THREAD

**Issue by surendrakumar1992** [tananaev/traccar-web#272]

**Comment by surendrakumar1992** [comment]
@tananaev  Hey Man, Please help regarding this query.

**Comment by tananaev** [comment]
GT06 can send a few different types of messages. Usually the problem is that GPS data is sent in one message and status (which includes power) is sent in another. Traccar currently doesn't support messages without GPS info, so status messages are ignored by server.

**Comment by tananaev** [comment]
Please next time post your question only in main Traccar issue tracker. Don't use this one.
