### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by bernamaxim** [tananaev/traccar-web#273]
I found this problem.

![untitled](https://cloud.githubusercontent.com/assets/2969479/8980829/ad9c6b0e-36dd-11e5-8ee2-5ef41ad6e61a.png)

I found this error before null pointer when inspected element:

![untitled2](https://cloud.githubusercontent.com/assets/2969479/8981096/d5ead7f6-36df-11e5-8b60-bbba7f435701.png)

Thanks for advance

**Comment by tananaev** [comment]
Please don't log issues against `traccar-web` project. You are using new web interface which is part of the main `traccar` repository.

**Comment by bernamaxim** [comment]
I'm sorry

**Comment by tananaev** [comment]
Create an issue in the main project:

https://github.com/tananaev/traccar/issues
