### ISSUE TITLE
Traccar Server would not start

### ISSUE THREAD

**Issue by dkenterprise100** [tananaev/traccar-web#274]
I did the following and I'm able to build the traccar-server and obtained

tracker-server.jar

I also followed the steps:
http://traccar.litvak.su/installation.html

and finally started the server...but got the following error:

Error-logs:

INFO   | jvm 1    | 2015/07/31 23:03:47 | WrapperSimpleApp: 
INFO   | jvm 1    | 2015/07/31 23:03:47 | WrapperSimpleApp Error: Encountered an error running main:
INFO   | jvm 1    | 2015/07/31 23:03:47 | WrapperSimpleApp Error: java.io.FileNotFoundException: /opt/traccar/conf/traccar.cfg (No such file or directory)

I dont know how to generate traccar.log ?

**Comment by tananaev** [comment]
Old web interface is obsolete. If you still have an issue please report it here:

https://github.com/tananaev/traccar/issues
