### ISSUE TITLE
How do I change traccar web?

### ISSUE THREAD

**Issue by lucaspoo** [tananaev/traccar-web#275]
Hello,

How do I change traccar web?
I realized that all the pages are generated through the " extjs". do you have any suggestions on how I can change the layout , for example?

Other questio is: how to let the responsive site?
was compiled by the source code

Thanks !!

**Comment by tananaev** [comment]
Are you talking about new web interface or the old one? If the new one, you have created thread in the wrong place. If the old one, it doesn't use ExtJS.

**Comment by lucaspoo** [comment]
I'm talking about the new web interface. This: https://github.com/tananaev/traccar/tree/master/web

I have compiled all repository: https://github.com/tananaev/traccar
Everything is working fine, but do not know how I change something on the site.

Already, many thanks for the quick response.

**Comment by tananaev** [comment]
You just need to change JavaScript files under `web` directory.

If you want to compile minified version of the web interface (app.min.js), you can find instructions here:
https://www.traccar.org/build/

Please next time use correct issue tracker. This one is for the old web interface (see readme file).

**Comment by lucaspoo** [comment]
I really did not notice the correct area, excuse my ignorance lol

Thank you very much for your help! It was these instructions the site that I needed.
