### ISSUE TITLE
Nginx Proxy to local site.

### ISSUE THREAD

**Issue by dschense** [tananaev/traccar-web#276]
Hi, I have a little Problem.
Ajenti and suff is running very smooth. I found this in the web: https://www.traccar.org/
Its a GPS tracking server. It runs by default as a Java wrapper and runs a Server on local:8082 
I tried much to get it running with ajenti and nginx.

this is my Config for now. Maybe anybody can help me:

#AUTOMATICALLY GENERATED - DO NO EDIT!

server {
  server_name trackme.dschense.de;
  return 301 https://trackme.dschense.de$request_uri;

  location / {

      proxy_set_header        Host $host;
      proxy_set_header        X-Real-IP $remote_addr;
      proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header        X-Forwarded-Proto $scheme;
      proxy_pass                  http://localhost:8082;
      proxy_read_timeout      90;

      proxy_redirect      http://localhost:8082 https://trackme.dschense.de;
    }
 }

server {
    listen *:443 ssl;
    ssl_certificate /etc/ssl/certs/dschense.de.crt;
    ssl_certificate_key /etc/ssl/private/dschense.de.key;
    server_name trackme.dschense.de;

    access_log /var/log/nginx/trackmedschensede.access.log;
    error_log /var/log/nginx/trackmedschensede.error.log;

    root /srv/trackme.dschense.de/www;
    index index.html index.htm index.php;

    location ~ [^/]\.php(/|$) {

        fastcgi_index index.php;
        include fcgi.conf;
        fastcgi_pass unix:/var/run/ajenti-v-php-fcgi-trackmedschensede-php-fcgi-0.sock;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;

    }

}

    location ~ [^/]\.php(/|$) {

        fastcgi_index index.php;
        include fcgi.conf;
        fastcgi_pass unix:/var/run/ajenti-v-php-fcgi-trackmedschensede-php-fcgi-0.sock;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;

    }

}

I get a 403 Forbidden error wen accessing the site.

[error] 31606#31606: *2 directory index of "/srv/trackme.dschense.de/www/" is forbidden, client: 109.193.119.216, server: trackme.dschense.de, request: "GET / HTTP/1.1", host: "trackme.dschense.de"

**Comment by dschense** [comment]
Got it Working.

Traccar is running in /opt/traccar on port 8082 with localhost (8082 is blocked through iptables and fail2ban from outside)

Domain is listening on Port 443 with ssl.

This it the Top-Level Configuration:

server {
  server_name trackme.dschense.de;

  location / {
    proxy_pass http://127.0.0.1:8082;
    proxy_redirect off;
    proxy_buffering off;
    proxy_set_header    Host            $host;
    proxy_set_header    X-Real-IP       $remote_addr;
    proxy_set_header    X-Forwarded-For $proxy_add_x_forwarded_for;
    port_in_redirect off;
    proxy_connect_timeout       900;
    proxy_send_timeout          900;
    proxy_read_timeout          900;
    send_timeout                900;
  }
}

**Comment by tananaev** [comment]
Thanks for sharing the info.

**Comment by dschense** [comment]
No problem ;-) 

I tested so many things to get it running.. After some hours I put my head on the table and wrote this issue.. 

And woops.. After writing theses lines everything was running well.. Grrrrr 

Maybe this helps someone not to have to search the web for hours ;-) 

cheers
