### ISSUE TITLE
[suggestion] Improve websocket documentation / usability for reverse proxies

### ISSUE THREAD

**Issue by SudoHenk** [tananaev/traccar-web#277]
Hi, I really like the project and I've just set it up for myself.

But, I wanted to place the GUI behing a Nginx reverse proxy to apply SSL to the connection, but this was harder than I thought.

First you need to make sure that Nginx allows websocket by adding this:
```
location / {
        proxy_pass http://127.0.0.1:8082;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }
```
Second part:
Edit app.min.js (placed in /opt/traccar/web/) and replace ws:// by wss://:
```
cd /opt/traccar/web/
sed -i 's/ws/wss/g' app.min.js
```

Now here is my suggestion: Please replace the ws:// with // (I think this will work with websockets too). That probably solves a lot of trouble shooting for newer fokes. Thanks!

**Comment by tananaev** [comment]
First of all, you created issue in a wrong project. It should be here:

https://github.com/tananaev/traccar/issues

As for the problem, it's already fixed in the latest code.

**Comment by SudoHenk** [comment]
Ok, sorry! Thanks for the update ;).

**Comment by kirantpatil** [comment]
@SudoHenk, can you please post your nginx configuration file ?
