### ISSUE TITLE
Commands?

### ISSUE THREAD

**Issue by manjoel** [tananaev/traccar-web#279]
Hi,

i tried to send commands I use an gps303 on port 5001 protocol 103.

In the list the command disarm Alarm was listed but in the log 

"Caused by: java.lang.RuntimeException: Command alarmDisarm is not supported in protocol gps103"

where could I find the list of working commands for the protocols.

Greeds

**Comment by tananaev** [comment]
You can find a list of supported commands for GPS103 protocol here (for version 3.3):

https://github.com/tananaev/traccar/blob/v3.3/src/org/traccar/protocol/Gps103Protocol.java
