### ISSUE TITLE
Logging into Traccar from a remote PHP program

### ISSUE THREAD

**Issue by topogigio** [tananaev/traccar-web#280]
Hi, 
regarding this topic https://github.com/tananaev/traccar-web/issues/248
I use traccar 3.4, the last version on windows server, so I need to have a jar file instead of war.
how can I solve?
Thanks

**Comment by vitalidze** [comment]
You need to follow official installation instructions from here: http://traccar.litvak.su/installation.html Then most probably you will need to follow these:  #509 #519 #520 #521

**Comment by tananaev** [comment]
Official Traccar version has a web API as well:

https://www.traccar.org/traccar-api/
