### ISSUE TITLE
Install traccar instructions

### ISSUE THREAD

**Issue by poobaisle** [tananaev/traccar-web#285]
Hello,
Is there a step by step manual to install traccar on Ubuntu Server 16.04 LTS please ? I tried with this one (https://www.traccar.org/forums/topic/how-to-install-traccar-server-on-aws-amazon-step-by-step-tutorial-2/) but I was prompted several times to choose different options during the installation process and it is not said what I should do. On top of that, I am stuck with the vi command which let me edit the linux.cfg file but gives an error when I try to register the file ("/opt/traccar/conf/linux.cfg" E212: Can't open file for writing). I tried with nano instead but no better result...
Is there a more detailed and updated step by step installation guide for traccar v3.6 somewhere ?
Thank you folks !

**Comment by tananaev** [comment]
First of all, this is not the right place to ask questions about Traccar. You should ask here:
https://github.com/tananaev/traccar/issues

As for installation, please download official release and follow README instructions:
https://www.traccar.org/download/

I wouldn't recommend following any outdated forum instructions unless you know what you are doing.
