### ISSUE TITLE
Need help calling the API

### ISSUE THREAD

**Issue by stevenseh** [tananaev/traccar-web#290]
As far as I understand, I would retrieve my positions using API with the below website.

http://demo.traccar.org/api/position/get?deviceId:911579&from:2016-10-02T02:00:00.000Z&to:2016-10-03T10:00:00.000Z

It does return an empty list, although there were several positions logged on the demo server.

What am I doing wrong?

Thanks for any help!

**Comment by tananaev** [comment]
What's the HTTP response code? I suspect that are just not authenticated.

**Comment by stevenseh** [comment]
There is no response code, it returns {}.
How would I authenticate?

**Comment by stevenseh** [comment]
Hi there Anton,
I saw that already, but it didn't get me any further. How do these methods
work in practice? Can the authentication be embedded in the web address?
I want either to call the API straight in browser, or use a Visual Basic
script to call it. I didn't find any usable (to me) info in the forums
about that...
Help is appreciated!
Thanks,
Eric

**Comment by tananaev** [comment]
You can add authorization header:

https://en.wikipedia.org/wiki/Basic_access_authentication

**Comment by stevenseh** [comment]
Thanks for that. I had already looked at that and tried multiple ways of
implementing that without success.
My latest try is:

Imports System.Net
Imports System.Text
Dim request as WebRequest = WebRequest.Create("http://
demo.traccar.org/api/position/get?deviceId:911579&from:2016-
10-02T02:00:00.000Z&to:2016-10-03T10:00:00.000Z")

Dim authInfo as string = "email" + ":" + "pw"
  authInfo = Convert.ToBase64String(Encoding.Default.GetBytes(authInfo))
  request.Headers("Authorization") = "Basic " + authInfo
Dim response = request.GetResponse()


this yields n error message: .The remote server returned an error: (404)
Not Found.

What am I still doing wrong?
Thanks again for your help!
Eric

**Comment by stevenseh** [comment]
Seems to be an issue with passing parameters, as my calls of
http://demo.traccar.org/api/devices/ and
http://demo.traccar.org/api/positions/ work just fine...
I tried all combinations I can think of....
Strange thing is that the deviceId that devices API returns is not the same
as the one on the app.
Could you send me an example of how to format the parameters for the call
with device and date parameters?
Thanks for looking into this.
Eric

**Comment by tananaev** [comment]
You need to use "=" instead of ":" for parameters. Where did you even get colons from?

**Comment by stevenseh** [comment]
I got those from the API documentation... I guess they come from the json
format. Anyways, I had already corrected that based on some info from the
forums, and it still does not work...
http://demo.traccar.org/api/positions/get?deviceId=32188&from=2016-10-2T02:00.000Z&to=2016-10-3T10:00.000Z
"

To repeat my questions: Which device # should I use? the one the device API?

What else is wrong with the http address I'm using, as it does not work as
it is...

Please send me an address that works...

Thanks,
Eric

**Comment by tananaev** [comment]
You need to use internal device id the one you get from the API. Have you encoded special characters (e.g. colon)?

**Comment by stevenseh** [comment]
I did not use colon in the name, or any other place that I recall.

Here is what I get from the API  w/o parameters:


[{"id":36368135,"attributes":{"battery":"0","ip":"172.73.242.171","distance":0.0,"totalDistance":15.22},"deviceId":4179,"type":null,"protocol":"osmand","serverTime":null,"deviceTime":"2016-10-03T22:39:41.000+0000","fixTime":"2016-10-03T22:39:41.000+0000","outdated":false,"valid":true,"latitude":35.081292,"longitude":-80.626563,"altitude":191.812,"speed":0.0,"course":0.0,"address":null}]

neither of the numbers 36368135 or 4179 work.
here is my http address
http://demo.traccar.org/api/positions/get?deviceId=32188&
from=2016-10-2T02:00.000Z&to=2016-10-3T10:00.000Z

This last run is on demo2 server, the main one seems to be down.

Thanks,
Eric

**Comment by tananaev** [comment]
You use colon in the date. That should be encoded.

**Comment by stevenseh** [comment]
I have colon in the time only. How should I code it? please correct my
http...

http://demo.traccar.org/api/positions/get?deviceId=32188&fro
m=2016-10-2T02:00.000Z&to=2016-10-3T10:00.000Z

**Comment by tananaev** [comment]
All the information your are asking is available on the Internet. There is nothing special about Traccar web API.

If you want a usage example, you can look at the default web interface.

**Comment by stevenseh** [comment]
I've been working on getting this to work for 2 days now. I've found some
examples in the forums which I copied, but they don't work. Where is the
default web interface that you are talking about?
All I'm asking for is a working example of a http address. Please send me
one, and I'll use it.
As far as I can tell, the one I'm using now should work, but it doesn't.

**Comment by tananaev** [comment]
Web interface is here:

https://github.com/tananaev/traccar-web

You can install Traccar locally and check requests that it sends:

https://www.traccar.org/download/

**Comment by stevenseh** [comment]
I found and followed instructions to install the download, but is stops a
few seconds after launch.
Here is the log:

STATUS | wrapper  | 2016/10/04 15:58:06 | --> Wrapper Started as Service
STATUS | wrapper  | 2016/10/04 15:58:06 | Java Service Wrapper Community
Edition 64-bit 3.5.28
STATUS | wrapper  | 2016/10/04 15:58:06 |   Copyright (C) 1999-2016 Tanuki
Software, Ltd. All Rights Reserved.
STATUS | wrapper  | 2016/10/04 15:58:06 |
http://wrapper.tanukisoftware.com
STATUS | wrapper  | 2016/10/04 15:58:06 |
STATUS | wrapper  | 2016/10/04 15:58:06 | Launching a JVM...
INFO   | jvm 1    | 2016/10/04 15:58:07 | WrapperManager: Initializing...
INFO   | jvm 1    | 2016/10/04 15:58:08 | [WrapperSimpleAppMain] INFO
com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Started.
INFO   | jvm 1    | 2016/10/04 15:58:09 | INFO 10/4/16 3:58 PM: liquibase:
Clearing database change log checksums
INFO   | jvm 1    | 2016/10/04 15:58:09 | INFO 10/4/16 3:58 PM: liquibase:
Successfully acquired change log lock
INFO   | jvm 1    | 2016/10/04 15:58:09 | INFO 10/4/16 3:58 PM: liquibase:
Successfully released change log lock
INFO   | jvm 1    | 2016/10/04 15:58:09 | INFO 10/4/16 3:58 PM: liquibase:
Successfully acquired change log lock
INFO   | jvm 1    | 2016/10/04 15:58:12 | INFO 10/4/16 3:58 PM: liquibase:
Reading from PUBLIC.DATABASECHANGELOG
INFO   | jvm 1    | 2016/10/04 15:58:12 | INFO 10/4/16 3:58 PM: liquibase:
Reading from PUBLIC.DATABASECHANGELOG
INFO   | jvm 1    | 2016/10/04 15:58:12 | INFO 10/4/16 3:58 PM: liquibase:
Successfully released change log lock
INFO   | jvm 1    | 2016/10/04 15:58:12 | [WrapperSimpleAppMain] INFO
org.eclipse.jetty.util.log - Logging initialized @5288ms
INFO   | jvm 1    | 2016/10/04 15:58:13 | WrapperSimpleApp:
INFO   | jvm 1    | 2016/10/04 15:58:13 | WrapperSimpleApp Error:
Encountered an error running main:
INFO   | jvm 1    | 2016/10/04 15:58:13 | WrapperSimpleApp Error:
org.jboss.netty.channel.ChannelException: Failed to bind to:
0.0.0.0/0.0.0.0:5006
INFO   | jvm 1    | 2016/10/04 15:58:13 | WrapperSimpleApp Error: at
org.jboss.netty.bootstrap.ServerBootstrap.bind(ServerBootstrap.java:272)
INFO   | jvm 1    | 2016/10/04 15:58:13 | WrapperSimpleApp Error: at
org.traccar.TrackerServer.start(TrackerServer.java:136)
INFO   | jvm 1    | 2016/10/04 15:58:13 | WrapperSimpleApp Error: at
org.traccar.ServerManager.start(ServerManager.java:73)
INFO   | jvm 1    | 2016/10/04 15:58:13 | WrapperSimpleApp Error: at
org.traccar.Main.main(Main.java:38)
INFO   | jvm 1    | 2016/10/04 15:58:13 | WrapperSimpleApp Error: at
sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
INFO   | jvm 1    | 2016/10/04 15:58:13 | WrapperSimpleApp Error: at
sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
INFO   | jvm 1    | 2016/10/04 15:58:13 | WrapperSimpleApp Error: at
sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
INFO   | jvm 1    | 2016/10/04 15:58:13 | WrapperSimpleApp Error: at
java.lang.reflect.Method.invoke(Unknown Source)
INFO   | jvm 1    | 2016/10/04 15:58:13 | WrapperSimpleApp Error: at
org.tanukisoftware.wrapper.WrapperSimpleApp.run(WrapperSimpleApp.java:325)
INFO   | jvm 1    | 2016/10/04 15:58:13 | WrapperSimpleApp Error: at
java.lang.Thread.run(Unknown Source)
INFO   | jvm 1    | 2016/10/04 15:58:13 | WrapperSimpleApp Error: Caused
by: java.net.BindException: Address already in use: bind
INFO   | jvm 1    | 2016/10/04 15:58:13 | WrapperSimpleApp Error: at
sun.nio.ch.Net.bind0(Native Method)
INFO   | jvm 1    | 2016/10/04 15:58:13 | WrapperSimpleApp Error: at
sun.nio.ch.Net.bind(Unknown Source)
INFO   | jvm 1    | 2016/10/04 15:58:13 | WrapperSimpleApp Error: at
sun.nio.ch.Net.bind(Unknown Source)
INFO   | jvm 1    | 2016/10/04 15:58:13 | WrapperSimpleApp Error: at
sun.nio.ch.ServerSocketChannelImpl.bind(Unknown Source)
INFO   | jvm 1    | 2016/10/04 15:58:13 | WrapperSimpleApp Error: at
sun.nio.ch.ServerSocketAdaptor.bind(Unknown Source)
INFO   | jvm 1    | 2016/10/04 15:58:13 | WrapperSimpleApp Error: at
org.jboss.netty.channel.socket.nio.NioServerBoss$RegisterTask.run(NioServerBoss.java:193)
INFO   | jvm 1    | 2016/10/04 15:58:13 | WrapperSimpleApp Error: at
org.jboss.netty.channel.socket.nio.AbstractNioSelector.processTaskQueue(AbstractNioSelector.java:391)
INFO   | jvm 1    | 2016/10/04 15:58:13 | WrapperSimpleApp Error: at
org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:315)
INFO   | jvm 1    | 2016/10/04 15:58:13 | WrapperSimpleApp Error: at
org.jboss.netty.channel.socket.nio.NioServerBoss.run(NioServerBoss.java:42)
INFO   | jvm 1    | 2016/10/04 15:58:13 | WrapperSimpleApp Error: at
org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
INFO   | jvm 1    | 2016/10/04 15:58:13 | WrapperSimpleApp Error: at
org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
INFO   | jvm 1    | 2016/10/04 15:58:13 | WrapperSimpleApp Error: at
java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
INFO   | jvm 1    | 2016/10/04 15:58:13 | WrapperSimpleApp Error: at
java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
INFO   | jvm 1    | 2016/10/04 15:58:13 | WrapperSimpleApp Error: ... 1 more
STATUS | wrapper  | 2016/10/04 15:58:16 | <-- Wrapper Stopped


What could have caused this?
I hope you can help.

Another question is about the web interface. How do I install it? What is
the difference with launching localhost:8082?

Thanks,
Eric

**Comment by tananaev** [comment]
The problem is that you already have some other process using port 5006:
```
Failed to bind to: 0.0.0.0/0.0.0.0:5006
```

Please answer directly on GitHub because it's not possible to format email comments properly.

**Comment by stevenseh** [comment]
OK... what to do about it.
I was checking open port scan and that port does not seem to be used... Het is the log:
Port Scanner will scan your computer for listening network ports. Each open port will be reported along with its common usage.
Hit "Start" to start a new scan.
Starting new scan: 2016-10-04 17:06:39
-----------------------------------
Port 135 commonly used for Remote Procedure Call servers is open
Port 445 commonly used for Microsoft Directory Service servers is open
-----------------------------------
Port 5000 commonly used for commplex-main servers is open
Port 5001 commonly used for commplex-link servers is open
Port 5002 commonly used for SOLICARD ARX servers is open
Port 5003 commonly used for FileMaker servers is open
Port 5004 commonly used for RTP (Real-time Transport Protocol) media data (RFC 3551, RFC 4571) servers is open
Port 5005 commonly used for RTCP (Real-time Transport Protocol) control protocol (RFC 3551, RFC 4571) servers is open
Port 5006 (unknown) is open
Port 5357 commonly used for Web Services on devices servers is open
Port 12025 (unknown) is open
Port 12110 (unknown) is open
Port 12119 (unknown) is open
Port 12143 (unknown) is open
Port 12465 (unknown) is open
Port 12563 (unknown) is open
Port 12993 (unknown) is open
Port 12995 (unknown) is open
Port 17500 commonly used for Dropbox LanSync Protocol (db-lsp) servers is open
Port 26143 (unknown) is open
Port 27275 (unknown) is open
-----------------------------------
Port 51829 (unknown) is open
-----------------------------------
Done performing scan: 2016-10-04 17:07:24

**Comment by tananaev** [comment]
Well, you need to either change the port in the config, or stop the process that uses it.

**Comment by stevenseh** [comment]
OK. I changed the config. Now traccar runs, but the devices fail to send to my server. I used the ip address that the quickstart page listed.
I'm at a loss again...
Help please!
Eric

**Comment by tananaev** [comment]
Check this page:

https://www.traccar.org/troubleshooting/

**Comment by stevenseh** [comment]
Hi there again.
My server hasn't received anything yet, and the port checking tool shows my ports as closed. I opened one of them in my firewall, but still, the app on my iPhone fails sending info to my server.
I disabled avast virus scan, and Spybot s&d, but to no avail. The ports still shows closed in the checking tool. What else might be causing the port to show closed?
Any help is appreciated! I would really want to use this service!
Thanks,
Eric

**Comment by tananaev** [comment]
Are you sure your ISP provides you a public IP address?

You need to forward ports on your router.

**Comment by stevenseh** [comment]
I do have a public IP address. Your site and some others show it.
I have a netgear CM400 router. I don't see any options to do port forwarding in the router settings. Another thing is that it seems that you need a static ip address for for forwarding. Is that correct? I don't have that either.
Looks like I'm at a loss here again...

**Comment by tananaev** [comment]
You don't need static IP for port forwarding, but you need to have a dedicated public IP address, not a one behind NAT.

**Comment by stevenseh** [comment]
CM400 is my modem... Port forwarding worked OK on the router.
The devices report OK to the local server.
However, I don't know how to call the API on my local server. If I use my public ip address, it times out. If I use localhost:8082, it refuses to connect. Error is ConnectFailure (Connection refused).
I don't think it's a firewall issue, unless I need to open another port. Right now, I only opened 5055.
How do I troubleshoot these issues? Are there logs that I can look at? I didn't see much in the tracker log or the server log.
Is this where the web interface comes in that you mentioned before? I found some installation instructions on http://traccar.litvak.su/installation.html. Is that what I need to do?
Thanks for helping me again!
Eric

**Comment by tananaev** [comment]
Are you using official version of Traccar? If yes, port 8082 should be the port for web interface.

Litvak's version if not an official Traccar version. If you want to use official one, that instructions is not for you.

**Comment by stevenseh** [comment]
I am using the official version.
I opened port 8082, and now I can call the devices API OK at that port.

Still remains the issue of calling the devices API with parameters for date and device.

How can I see what traccar server received as request, and what the error messages are. Is there a log generated? The only log I know about is the tracker log, and I did not see anything in the tracker log other than the reports from the devices.

Is the web interface at https://github.com/tananaev/traccar-web helping with troubleshooting? If yes, how can I install it.

Another thing that might help me is looking at the code. Can you point me to the code of the API?

Thanks,
Eric

**Comment by tananaev** [comment]
It's a REST API. For errors you need to check both HTTP result code and response content for more details.

I don't really get the question about troubleshooting. That's the web interface that you should be using.

API code is here:

https://github.com/tananaev/traccar/tree/master/src/org/traccar/api

**Comment by stevenseh** [comment]
I get response: The remote server returned an error: (404)
Not Found.

I don't know how to check the return code. The only result I get from the API call is the string that it's returning. Is there a way to get that http return code from my vb script?

Wit troubleshooting the API I meant that maybe there is a log that I don't know about that ma ybe logging info passed to the API, results from intermediate steps, warning messages for incorrect calls, things of that nature). From your response, I gather that there is no log to consult that would help me debugging the API. Is that correct? 

In the meanwhile I'll have a look at the code. 
Thanks,
Eric

**Comment by tananaev** [comment]
There is no logging of API calls.

404 is the response code, so you already get it.

I think you are still not authorized, that's why you get the error.

**Comment by tananaev** [comment]
Wait wait wait... where did you get "/api/position/get" from? It should be "/api/positions".

**Comment by stevenseh** [comment]
I'm pretty sure I'm authorized as the calls for devices and the latest position (positions w/o params) are working fine.

**Comment by tananaev** [comment]
See my last comment. Your URL path completely incorrect. I don't even know where you got it.

**Comment by stevenseh** [comment]
Dim request as WebRequest = WebRequest.Create("http://xxxxx:8082/api/positions/get?deviceId=3&from=2016-10-02T02:00:00.000Z&to=2016-10-06T20:00:00.000Z")

This is my call...

**Comment by stevenseh** [comment]
I tried many different ways. That's why I've been asking for a string this is working... I prefer US date format, but I could use any other format as well.

**Comment by tananaev** [comment]
Please read my comments very carefully. I already told you what's wrong and what you should be using.

**Comment by stevenseh** [comment]
You have helped me along in quite some instances, but on this issue with the positions API using parameters, you are not very helpful. I'm sorry to have to say that.

I'm obviously not the only person with this issue, and with the request for an example - see https://www.traccar.org/forums/topic/cannot-use-api-apipositionget/

Now please tell me what I need to change to make this call work:

Dim request as WebRequest = WebRequest.Create("http://xxxxx:8082/api/positions/get?deviceId=3&from=2016-10-02T02:00:00.000Z&to=2016-10-06T20:00:00.000Z")

I tried encoding the ":" in the time as "%3A", but I get the same error.

Thanks,
Eric

**Comment by tananaev** [comment]
Please read this comment:
> where did you get "/api/position/get" from? It should be "/api/positions"

**Comment by stevenseh** [comment]
I know it's /api/positions . What about the parameters? I tried /deviceid... and ?deviceid. Neither Does not work. For heavens sake, please send me the whole string...

**Comment by stevenseh** [comment]
Please don't keep me guessing.

**Comment by tananaev** [comment]
Here is an example of correct URL:
```
http://demo.traccar.org/api/positions?deviceId=1&from=2016-10-07T21%3A56%3A06.000Z&to=2016-10-07T22%3A26%3A06.000Z
```

**Comment by stevenseh** [comment]
The winner is:

Dim request as WebRequest = WebRequest.Create("http://xxx:8082/api/positions?deviceId=3&from=2016-10-02T00:00:00.000Z&to=2016-10-06T23:59:59.000Z")

The one with the : encoded as %3A gave a return code 400 Bad Resquest

Thanks for hanging in there...
Eric

**Comment by tananaev** [comment]
It probably means that `WebRequest.Create` encode URL automatically.
