### ISSUE TITLE
Start & stop data flow from a tracker device

### ISSUE THREAD

**Issue by mcriasia** [tananaev/traccar-web#33]
It would be nice to call the platform server software up and then have the ability to start and stop each device from adding captured data to the buffer logs.  This will keep the logs from over-running with data from multiple devices and the user will have the ability to toggle devices on and off with out sending a command to the device.  The ability to send commands to a device such as arm, disarm, set time, reset, track time, geo fence, and toggle SMS mode would be great too.

**Comment by tananaev** [comment]
Commands are now supported (versions 3.1+).
