### ISSUE TITLE
Cannot start service with mysql db

### ISSUE THREAD

**Issue by sefelectronics** [tananaev/traccar-web#332]
Hello there, I'm facing a problem while trying to start the service with mysql db, the error it shows is about encoding

    jvm 1    | WrapperSimpleApp Error: Encountered an error running main:
    jvm 1    | WrapperSimpleApp Error: com.sun.org.apache.xerces.internal.impl.io.MalformedByteSequenceException: Invalid byte 1 of 1-byte UTF-8 sequence.

If i use the default setting traccar start properly and i can track my device with no problem but it seems impossibile to stop the service and I need to reboot to stop it, it hangs waiting
There is also an error loading the wrapper 

    wrapper  | The value of wrapper.java.command does not appear to be a java binary.
    wrapper  | The use of scripts is not supported. Trying to continue, but some features may not work correctly..

I tried to force the actual path of java but the result is the same, what I've done in wrapper is 

    #wrapper.java.command=java
    set.JAVA_HOME=/usr/lib/jvm/java-1.7.0-openjdk-1.7.0.111-2.6.7.2.el7_2.x86_64/jre
    wrapper.java.command=%JAVA_HOME%/bin/java`

this is my config

    <entry key='database.driver'>com.mysql.jdbc.Driver</entry> 
    <entry key='database.url'>jdbc:mysql://localhost:3306/traccar_db?allowMultiQueries=true&amp;autoReconnect=true&amp;useUnicode=yes&amp;characterEncoding=UTF-8&amp;sessionVariables=sql_mode=ANSI_QUOTES</entry>
    <entry key='database.user'>traccar_usr</entry>     
    <entry key='database.password'>******</entry>

Any help would be much apreciated

**Comment by tananaev** [comment]
Is the issue solved?

**Comment by tananaev** [comment]
Never mind. I see you moved it into the main repo (https://github.com/tananaev/traccar/issues/2576).
