### ISSUE TITLE
How to enable Trip and Trip report

### ISSUE THREAD

**Issue by kirantpatil** [tananaev/traccar-web#336]
Hi,

I could see route report but not Trip report. I would like to know how it has to be enabled ? 
I don't see the Trip configuration either at admin or user page, since it mentions Start Address and End Address. I am using android mobile as device.

Thanks.

**Comment by kirantpatil** [comment]
Please find the attached screenshot.
![screenshot from 2016-11-25 16 29 38](https://cloud.githubusercontent.com/assets/1178055/20623199/70768cc4-b32c-11e6-80c8-dbc6185033b3.png)

**Comment by kirantpatil** [comment]
I found below configuration parameters from configuration page. Do I need to add all of them to default.xml file to enable Trip report ?

report.trip.minimalTripDuration	config	Trips less than minimal duration and minimal distance are ignored. 300 seconds and 500 meters are default.

report.trip.minimalTripDistance	config	Trips less than minimal duration and minimal distance are ignored. 300 seconds and 500 meters are default.

report.trip.minimalParkingDuration	config	Parking less than minimal duration does not cut trip. Default 300 seconds.

report.trip.greedyParking	config	If true, the device is considered to be in parking state and only continuous trips are detected.

**Comment by tananaev** [comment]
You don't need to add anything to the config to enable trips.

**Comment by kirantpatil** [comment]
Demo server (http://demo.traccar.org/) is not showing Trip report. Is it disabled in it ?

**Comment by tananaev** [comment]
There is no way to disable trips. If you don't see them, then it means data reported by your device doesn't allow to calculate trips.

**Comment by kirantpatil** [comment]
Yes, now I could see the Trip report as below, but it is not showing Start Address and End Address. How to get Start Address and End Address in Trip report ?

![screenshot from 2016-11-26 14 04 07](https://cloud.githubusercontent.com/assets/1178055/20639141/740629a2-b3e1-11e6-837c-a88e878396cc.png)

**Comment by tananaev** [comment]
You would have to use your own server and configure reverse geocoding.
