### ISSUE TITLE
Save toggle button status

### ISSUE THREAD

**Issue by tananaev** [tananaev/traccar-web#338]
I remember this was discussed before somewhere, but I'll just add it anyway so we don't forget.

It would be nice to save toggle button statuses. Got a request for this feature from one client.

Not a huge priority, but we can consider it at some point.

I guess the best option would be to save it in attributes.

**Comment by Abyss777** [comment]
I'm not sure that update user object on every toggle is a good idea.
Last time I suggested to store them in cookies.

**Comment by Abyss777** [comment]
Here #303

**Comment by tananaev** [comment]
I don't want to save it on every click, but maybe we can do something similar to how default location and zoom are saved. You go into account and there will be a button that will take current toggle values and save them in attributes.
