### ISSUE TITLE
Custom Commands for gps103 trackers

### ISSUE THREAD

**Issue by paraisotech** [tananaev/traccar-web#344]
All my trackers are gps103 and xexun devices.
I observed that the custom commands for gps103 only work if you send the complete sentence, for example.
H command + , + speed in kmph with 3 bytes (H,080 to set up an speed alert over 80km/h) doesn't work if you only send H,080 in the custom field. It will only work if you send the full sentence, for example(again):
```
**,imei:[the device imei numbers],H,080
```
My question is that if it is possible to put thix fixed information already in the field or even not to be necessary to type it, when the user send the command, the system fill it up in run time.

Here is the full gps103 command list that i found. I visited several sites and forums...
```
#A = STOP SENDING POSITIONS
#E = STOP SENDING EVENT ALARMS
#F,XXXm = ONLY SEND POSITIONS IF THE LAST VALID POSITION IS OVER THEN THE XXX METERS PARAMETER
#G = ACTIVATES THE MOVEMENT ALERT(200M RADIUS)
#H,XXX = ACTIVATES THE OVERSPEED ALERT
#I, (+/-)X = SET UP THE TIME ZONE. EX. I,-3 SETS UP THE TIME ZONE TO THE BRASILIA'S TIME
#J = STOP ENGINE
#K = START ENGINE
#L = TURN ON THE ALARM (ALSO (RE)ACTIVATES THE OPEN DOOR, IGNITION AND VIBRATION ALARMS)
#M = TURN OFF ALARM
#N = TURNS OFF GPRS MODE(ONLY CAN BE REACTIVATED BY SMS COMMAND)
#O, A,B,C,D = CREATES GEOFENCE BETWEEN THE COORDINATES A->B, B-C, C->D E D->A(ONLY A SQUARE POLYGON)
#P = DEACTIVATES GEOFENCE
#Q,YYYYMMDD = QUERIES THE DATA SAVED IN SD CARD. Y=YEAR WITH 4 BYTES, MONTH 2 BYTES AND DAY 2 BYTES
#S = STOP SENDIND SD SAVED DATA
#T = ACTIVATES THE POWERSAVE MODE(ONLY WHEN OPERATING BY SMS)
#V = QUERIES PHOTOS(IF AVAILABLE)
```
I hope this information be usefull as were for me...
@tananaev

**Comment by tananaev** [comment]
Implemented:

https://github.com/tananaev/traccar/commit/3593df6595cb1af169098ea2e7594fc3480648d0
