### ISSUE TITLE
[traccar-3.9] Registration Disable Bug

### ISSUE THREAD

**Issue by malevan** [tananaev/traccar-web#356]
Fresh server install.
Logged in as Admin.
When I uncheck checkbox 'Registration' in Settings>>Server. It does not disable 'register' button, the box remains checked when I go back into the Server settings.

**Comment by JuanIrache** [comment]
Hi, I have updated those 3 files and the issue remains the same. Both Registration and Readonly (which I used for testing) remain checked. Am I missing something?

**Comment by tananaev** [comment]
Yes, you are missing minified version of the web interface. You have two options:

1. Generate minified version using `tools/minify.sh` script
2. Add following line to the config:
```xml
<entry key='web.debug'>true</entry>
```

**Comment by JuanIrache** [comment]
Thanks, that did it

**Comment by punisher74** [comment]
Приветствую! Читаю и не понимаю, что нужно сделать, чтобы отключить регистрацию. Вставил в конфиг строку "<entry key='web.debug'>true</entry>", но не помогло, регистрация через настройки так и не отключается. Можно попросить подробную инструкцию, как это сделать?

**Comment by tananaev** [comment]
@punisher74, вы код обновили?

**Comment by punisher74** [comment]
Добрый вечер! Нет код я не обновил, не понимаю как его обновить, можно вас попросить мини манул по обновлению кода?

**Comment by tananaev** [comment]
Если вы не разбираетесь в коде, то советую подождать новой версии.

**Comment by chrystianmartins** [comment]
In my case I'm using windows 10, how to proceed?
