### ISSUE TITLE
How I know the port ?

### ISSUE THREAD

**Issue by leontino** [tananaev/traccar-web#357]
Hi everyone,

 How I know the port for this protocol

*HQ,13069100123456,V1,114218,A,344.9999,S,3222.4453,W,0.9,0.0,131216,FFFFFBFF#

**Comment by gpproton** [comment]
Use port 5013

 

Godwin Peter .O  

Cloud | GIS Professional
 <mailto:godwin@peter.com.ng> godwin@peter.com.ng

+2348062957703

**Comment by leontino** [comment]
Thank you so much! How do you know that ?

**Comment by tananaev** [comment]
You can use this guide:

https://www.traccar.org/identify-protocol/
