### ISSUE TITLE
Openlayers 3.20.0 update

### ISSUE THREAD

**Issue by Abyss777** [tananaev/traccar-web#361]
Some time ago 3.20.0 was released.
It has significant change to us, image setter for ol.style.Style http://openlayers.org/en/v3.20.0/apidoc/ol.style.Style.html

I very much hope this will solve issues with incorrect device images.

I'm going to test it.

**Comment by tananaev** [comment]
Feel free to update it if it fixes the problem.

**Comment by Abyss777** [comment]
I've tried and got flickering again. It looks less than full style recreation, but still...

I think that flickering is the lesser evil than inconsistent device images on map. Especially it is very rare case then device is updated every second.

I tend to migrate to 3.20.0, use `setImage()`, accept the blinking and look forward implementation of image `src` setter.

@tananaev what do you think?

**Comment by tananaev** [comment]
I agree, it's better to show valid information and have some flickering that we can solve later.

**Comment by Abyss777** [comment]
Closed with #364
