### ISSUE TITLE
Yandex maps support

### ISSUE THREAD

**Issue by Abyss777** [tananaev/traccar-web#366]
I've found the solution, not so easy, but possible. It uses external library https://github.com/proj4js/proj4js for coordinates conversion.

http://gis-lab.info/forum/viewtopic.php?f=19&t=19763#p147223
http://gis.stackexchange.com/questions/187082/openlayers-3-projection-for-yandex-maps
https://jsfiddle.net/_DR_/e9vnmv0w/21/

May be it is worth to be implemented.

**Comment by tananaev** [comment]
Yes, I have researched it before. It's possible, but I'm not sure how valuable it is. Yandex Maps would be valuable only in some regions (mostly post-USSR countries).

**Comment by Abyss777** [comment]
I have the same doubts about its value.

**Comment by tananaev** [comment]
Decided to add some new map layers, including Yandex (Russia) and Baidu (China).
