### ISSUE TITLE
[UX] When adding a geofence area, use the current map position

### ISSUE THREAD

**Issue by amenk** [tananaev/traccar-web#373]
1. Add geofence
2. Click area
3. Map is zoomed to somewhere

Better:

3. Map is zoomed to the current main map position

**Comment by tananaev** [comment]
I was actually thinking that we should just use main map for geozone creation.

**Comment by amenk** [comment]
Good idea

**Comment by HenriqueKraemer** [comment]
What about a search field for an coordinate or address?

**Comment by tananaev** [comment]
That's also a good idea, but for address search we would have to use some third party service.

**Comment by HenriqueKraemer** [comment]
There is **Nominatim** from **openstreetmap** (it has a _public api_).

Refs: 
http://wiki.openstreetmap.org/wiki/Nominatim
https://wiki.openstreetmap.org/wiki/Nominatim_usage_policy

I guess it's possible to use even with another maps on Traccar, if we are talking about get the coordinates and load on the map (no matter which).

**Comment by HenriqueKraemer** [comment]
Work in progress...

<img width="1680" alt="captura de tela 2017-02-06 as 19 02 15" src="https://cloud.githubusercontent.com/assets/822026/22666259/00de01ce-ec9f-11e6-9127-307fa8419bba.png">
