### ISSUE TITLE
Bring selected icon to front

### ISSUE THREAD

**Issue by tananaev** [tananaev/traccar-web#374]
When we have many icons in one area, it would be nice to bring selected one to the front.

Another unrelated thing I was thinking about is to remove selection if you click outside of any icons on the map.

**Comment by amenk** [comment]
Good idea. Also https://github.com/Leaflet/Leaflet.markercluster might come in handy somehow.

**Comment by tananaev** [comment]
We don't use Leaflet. OpenLayers has own clustering mechanism.

Speaking of large number of things on the map, some people complain that a report is very slow if there are a lot of points. Maybe we can have an option to not show individual arrows for reports.

**Comment by Abyss777** [comment]
There are two options.
- change zIndex of marker style, it will bring marker to front on the same layer. (devices are lower than reports, that means that device will be higher than other devices, but report will be higher than other reports and devices)
- rethink the way we selecting devices and implement it with help of 'ol.interaction.Select`

**Comment by Abyss777** [comment]
Oh, my mistake, `ol.interaction.Select` won't help.
We need move selected feature to some upper layer...

**Comment by Abyss777** [comment]
About switching off report arrows... It should be toggle button like others, or user/server attribute will be enough?  I'm asking because it will be last button that can be placed on vertical mobile view 720x1280.

**Comment by tananaev** [comment]
I guess it can be a button for not... or it can be an option of the report itself.
