### ISSUE TITLE
Show results of sent commands

### ISSUE THREAD

**Issue by amenk** [tananaev/traccar-web#375]
Can results of issued commands be shown?
As the command-results may not always be linkable to the issued command, it might be enough to open the recent debug log after a command was issued.

Right now I always have to log to the server consule and `tail -f tracker-server.log`

**Comment by tananaev** [comment]
Traccar already shows command result.

**Comment by amenk** [comment]
Hm where?

**Comment by tananaev** [comment]
Result string should be a part of the message, if your device sends it.

**Comment by amenk** [comment]
You mean in the log? Found it somehow ... I was more thinking of a popup. But it's okay

**Comment by tananaev** [comment]
There is a popup if you subscribe for the notification.
