### ISSUE TITLE
Problem with imports

### ISSUE THREAD

**Issue by tananaev** [tananaev/traccar-web#380]
Some "requires" definitions are incorrect. For example:
```JavaScript
Ext.define('Traccar.view.DeviceDialog', {
    extend: 'Traccar.view.BaseEditDialog',

    requires: [
        'Traccar.view.BaseEditDialog'
    ],

    controller: 'baseEditDialog',
```

In this case, instead of importing `BaseEditDialog` which is already imported via `extend`, we should import `BaseEditDialogController` which is required for `baseEditDialog` controller.

I guess we should go through the code and find if there are any other similar issues.

**Comment by Abyss777** [comment]
I'm not sure that we should import `BaseEditDialogController` because we "import" it via `controller`.

I think in this case we should just remove `requires:`

**Comment by tananaev** [comment]
How would it know that `baseEditDialog` controller is in `BaseEditDialogController` class?

**Comment by Abyss777** [comment]
Looks like there is naming agreement and `Ext.Loader` loads automatically `BaseEditDialogController` when we define `extend: 'Traccar.view.BaseEditDialog'`.

We use `controller: 'baseEditDialog'` to link it to view by alias `controller.baseEditDialog`

**Comment by tananaev** [comment]
Can you please provide some links for the naming convention. I couldn't find anything.

**Comment by Abyss777** [comment]
I can't find full description too, but here is piece of information: https://docs.sencha.com/extjs/6.2.0/guides/application_architecture/application_architecture.html#application_architecture-_-application_architecture_-_file_structure

**Comment by Abyss777** [comment]
Also here
https://docs.sencha.com/extjs/6.2.0/guides/application_architecture/application_architecture.html#application_architecture-_-application_architecture_-_namespace

> // Core
// "MyApp.view.main.MainController" shared between toolkits would be located at:
app/view/main/MainController.js

**Comment by tananaev** [comment]
Yes, but where does it say that it will automatically import `BaseEditDialogController` if we extend `BaseEditDialog`? Also, in some cases we have name that doesn't fully match. For example `DeviceDistanceDialog` and `DeviceDistanceController`. I guess it should be `DeviceDistanceDialogController`.

Offtopic... I was thinking that we should split view classes into some meaningful subfolders. What do you think? For example, all map-related can go into "map" folder.

**Comment by Abyss777** [comment]
In case `DeviceDistanceDialog` we "require" `'Traccar.view.DeviceDistanceController'` and what is interesting it could not find `DeviceDistanceDialogController` after renaming.

OK. We should use "require" for controllers.

Also I would suggest use inheritance better, for example `BaseEditDialog`:

require controller `BaseEditDialogController` in `BaseEditDialog` and config `controller`

`DeviceDialog` and `GroupDialog` do not have own controllers, they will use `BaseEditDialogController` from parent by inheritance. They do not need `require` and `controller`

Other childs of `BaseEditDialog` replace parent controller, and they should have 'require` and `controller` configs.


I totally agree that we should split classes to subfolrders. To many files. We should invent schema how to split them.

**Comment by tananaev** [comment]
If controller inheritance works, I don't see why not. Makes sense to set it in the base class only.

As for subfolders, I guess it's better to create a separate thread.
