### ISSUE TITLE
Icon image updates

### ISSUE THREAD

**Issue by tananaev** [tananaev/traccar-web#384]
I noticed that on every update there is a new "network" request logged in the Chrome developer console:

![screen shot 2017-01-13 at 11 47 51 am](https://cloud.githubusercontent.com/assets/1161863/21911581/425f7c58-d986-11e6-88f1-6b21a1c8dc1e.png)

Not sure if it's an issue, but it can indicate some potential problem.

@Abyss777, what do you think?

**Comment by Abyss777** [comment]
I do not think it is a problem. 
Do not know why Chrome shows data uri like network activity, Firefox does not. You can see in Size column that real network activity is not happening.

**Comment by tananaev** [comment]
I know that there is no network activity. I'm just thinking that there might be some memory leak if browser caches all those images.

**Comment by Abyss777** [comment]
I checked it just after implementation and considered that garbage collector handles it correctly.

![image](https://cloud.githubusercontent.com/assets/5688080/22414311/3f260766-e6e0-11e6-91b6-3a21c0eea80e.png)

**Comment by tananaev** [comment]
OK, closing this issue. Thanks.
