### ISSUE TITLE
Add version tags to the web repository to avoid incompatibility with server.

### ISSUE THREAD

**Issue by gustavofcalmeida** [tananaev/traccar-web#396]
It would be nice to have version tags in this repository in the same fashion there are in traccar server repository.

**Comment by tananaev** [comment]
Seems like you are not very familiar with git submodes. For tags, main Traccar repository points to the exact commit that you should be using.

**Comment by gustavofcalmeida** [comment]
I figured this after a while, that's why I removed the second part of my comment. I left the suggestion, though. Thanks.

**Comment by tananaev** [comment]
Makes some sense. I'll do it for the next release.
