### ISSUE TITLE
how to manually adapt the track colors

### ISSUE THREAD

**Issue by Phantomatz** [tananaev/traccar-web#406]
With 3.10, I have 3 trackers running, and like to show the tracks, however, I would like to change the predefined colors to something which better fits to the device. I cannot find any parameter description to do so.

Any hint ?

**Comment by tananaev** [comment]
Colors indicate connection status. If you want to change it, you would have to modify the source code.

**Comment by stere0123** [comment]
He may be referencing track line colors, rather than device icons. I have also been unable to find a way to change track line colors displayed on the map when viewing routes/tracks.

**Comment by tananaev** [comment]
All the colors and styles are here:

https://github.com/tananaev/traccar-web/blob/master/web/app/Style.js

**Comment by Abyss777** [comment]
In addition, it is possible to override color of report/live route for device by setting Device attribute `web.reportColor`. HTML colors are accepted.

**Comment by Phantomatz** [comment]
Thank you Abyss777 thats what I have been looking for. Seems to work for me.
Is there a list for the Wrapper attributes, like it is available for the config parameters ?

**Comment by tananaev** [comment]
Yes, there is:

http://yajsw.sourceforge.net/YAJSW%20Configuration%20Parameters.html
