### ISSUE TITLE
Device readonly user

### ISSUE THREAD

**Issue by tananaev** [tananaev/traccar-web#411]
@Abyss777, I have heard a few complaints that readonly user can't send commands anymore. I propose that we allow "device readonly" user to send commands. The idea is that he can't add or remove devices, but he can still manage his own devices, including sending commands.

**Comment by tananaev** [comment]
Another related suggestion is to add "deviceReadonly" to the server settings as well, to be consistent with "readonly" flag.

**Comment by tanask** [comment]
I suggest to have an option to allow or not allow the user under read only to use commands

**Comment by tananaev** [comment]
@tanask, there is a "device readonly" flag for that.
