### ISSUE TITLE
Permissions check column to wide

### ISSUE THREAD

**Issue by Abyss777** [tananaev/traccar-web#413]
I suppose after this commit https://github.com/tananaev/traccar-web/commit/1db0f3fce321a6f22da47998a53f6a5bf7bc7b36
check column become too wide
![image](https://cloud.githubusercontent.com/assets/5688080/23158915/a26cf3b6-f842-11e6-805d-4a91b52f9c2b.png)

May be It should be adjusted some how.

**Comment by tananaev** [comment]
Agree. We should probably limit the size of the checkbox columns.

**Comment by Abyss777** [comment]
Unfortunately `columns.defaults` override `selModel.headerWidth`. I'll move default values to columns for permissions views.

**Comment by tananaev** [comment]
Sounds good, thanks.
