### ISSUE TITLE
Traccar Manager file upload

### ISSUE THREAD

**Issue by tananaev** [tananaev/traccar-web#418]
I have fixed https://github.com/tananaev/traccar-manager-android/issues/42, but now there is some JavaScript problem with upload:

![screen shot 2017-02-28 at 10 26 55 pm](https://cloud.githubusercontent.com/assets/1161863/23399497/4d8127fa-fe05-11e6-81e0-038ccb4d3d5a.png)

@Abyss777, can you take a look?

**Comment by Abyss777** [comment]
What is the size of file you tried to upload?

**Comment by Abyss777** [comment]
I think so. Calendar with 200 events takes about 47 kilobytes.

Here is samples with one event.
[Calenar samples.zip](https://github.com/tananaev/traccar-web/files/806629/Calenar.samples.zip)

**Comment by tananaev** [comment]
Thanks, I will try tomorrow.

**Comment by tananaev** [comment]
Works with your sample. Thanks.
