### ISSUE TITLE
Remembered password saved incorrectly

### ISSUE THREAD

**Issue by Abyss777** [tananaev/traccar-web#419]
Chars in password are replaced by html codes in cookie store, for example `pa$$word` by `pa%24%24word`. 

![image](https://cloud.githubusercontent.com/assets/5688080/23493016/72adadc0-ff2a-11e6-9de7-399b8784c299.png)

And then passed to server as is and login fails.

![image](https://cloud.githubusercontent.com/assets/5688080/23493041/b4e65ea8-ff2a-11e6-98be-b55471a608dd.png)

**Comment by Abyss777** [comment]
I investigated a bit and find out that `Ext.util.Cookies.set()` http://docs.sencha.com/extjs/6.2.0/classic/src/Cookies.js.html#Ext.util.Cookies-method-set uses deprecated metod `escape()` https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/escape

There is no good way to "unescape" it on the Java side.

I think we have to set cookies in other way and use `encodeURIComponent()` on JS side and `URLDecoder.decode()` on the Java side.

**Comment by tananaev** [comment]
I think we can encode cookies in base64 or hex.

**Comment by Abyss777** [comment]
Yes, base64 is something standard for html. One small thing is that base64 string will have "=" at the end and will (and should) be escaped in cookies.
But it is not a big problem, because `URLdecoder.decode()` easily copes with it. I've got an working code for both and will make a PR.
