### ISSUE TITLE
I see my device on demo.traccar.org but I don't see something updated on my added device

### ISSUE THREAD

**Issue by SokhengNget** [tananaev/traccar-web#430]
Excuse me, Sir. I don't see something updated on my traccar.org after I've added device to it. Help me please.

**Comment by tananaev** [comment]
Do you want me to guess? You have to provide some information about the problem.

**Comment by SokhengNget** [comment]
Yes.

**Comment by tananaev** [comment]
OK, I'm closing this one. Reopen if you decide to provide information.
