### ISSUE TITLE
Wrong Added or my gps isn't connected

### ISSUE THREAD

**Issue by SokhengNget** [tananaev/traccar-web#431]
I've added device to traccar.org already. But after I click on it and it show nothing. Do I add wrong field on Device added form? or my gps device doesn't work? But I've tested my device with command url# And it replied right location on Google Map to me. Thanks in advanced.

**Comment by tananaev** [comment]
Please don't spam everywhere. You already created one thread.

**Comment by SokhengNget** [comment]
No. I ask you what my problem meet.

**Comment by tananaev** [comment]
I won't be able to help you if you don't provide any information.

**Comment by SokhengNget** [comment]
My problems is like this problem "Tk103-2 via demo server? #1310". 
I am not seeing anything in my traccar account. I have followed the device/port list (5023 for GT06N), but nothing happened. IMEI number is 358899050753113. Any idea what am I doing wrong here? I am using as demo.traccar.org IP address. Please help me.

**Comment by tananaev** [comment]
I have checked server logs and there is nothing from device with this id, which means that your device doesn't send anything to the server.

**Comment by SokhengNget** [comment]
But I check it with command URL# from my phone and it return right location when I check with link in Google Map. Anything wrong with it?

**Comment by jeepeto** [comment]
Are you using gprs?

**Comment by SokhengNget** [comment]
Yes. I use command "SERVER,1, demo.traccar.org,5023,0#" to point my device to demo.traccar.org server. Anything wrong?

**Comment by tananaev** [comment]
Still nothing from your device. I guess device just doesn't work or it's misconfigured. I would recommend contacting device vendor support.

**Comment by SokhengNget** [comment]
Isn't the demo server 1 not support some port? Cos I saw "Demo server 1 (some ports are unavailable)" on it. If I change to server 2 or 4, is it ok?

**Comment by tananaev** [comment]
Port 5023 is definitely open.

**Comment by SokhengNget** [comment]
All server?

**Comment by tananaev** [comment]
Yes.

**Comment by SokhengNget** [comment]
So let me change to server 4. And I will ask you again if anything wrong.

**Comment by SokhengNget** [comment]
Sir, I follow this instruction "http://www.iconcox.com/uploads/soft/130711/1-130G11F117.pdf". but I still can't point it to demo server 1. Am I getting something wrong?

**Comment by tananaev** [comment]
I don't know. You should contact devices vendor support.

**Comment by SokhengNget** [comment]
ok.
