### ISSUE TITLE
Inconsistency with store loading

### ISSUE THREAD

**Issue by tananaev** [tananaev/traccar-web#441]
I noticed that in `GeofencesController` we load `Geofences` and `Calendars` stored. Do we really need to do that? It means every time we open the dialog, we do two requests. Geofences should be loaded on startup. Maybe we should do same thing with calendars as well.

@Abyss777, what do you think?

**Comment by Abyss777** [comment]
Frankly,  I do not remember, why `Geofences` loaded twice and `Calendars` not loaded on startup, but I will check all stores loads if they are really necessary.

**Comment by tananaev** [comment]
Thanks. I think it makes sense to load most stored on startup because it's asynchronous anyway. One exception I can think of is all users because there can be a lot of data.

**Comment by Abyss777** [comment]
Agree, Users used only then dialog is open and they are not related to other parts.

**Comment by Abyss777** [comment]
Don't you also mean load "All*" stores for admin and manager?  I think it is not necessary or ...

**Comment by tananaev** [comment]
Probably doesn't make much sense to do it for "All*" stores.
