### ISSUE TITLE
Save state of buttons, grids and panels

### ISSUE THREAD

**Issue by Abyss777** [tananaev/traccar-web#446]
My suggestion is:

- Save state of buttons on the map tool bar
- Save state of viewport/panels width/height collapsed or not
- May be add more columns and save state of Users grid

Another question is what will we do with current way of save/restore buttons state? Remove it or combine?
For example: 
- Cookies have priority, if empty apply user or server attributes
- Or vise versa, cookies are applied only if users or server attributes are absent.

**Comment by tananaev** [comment]
Agree with saving map toolbar and panels.

I don't think we need to add anything to users table or save its state. What we can add there is search like in devices. For example on demo server there are 10k+ users and it's very hard to find something in list that long.

I think we should remove current way of saving button states. It would make code simpler and also UI simpler as well. There will be no extra button in user dialog that everyone is asking about. What do you think?

**Comment by Abyss777** [comment]
I was thinking about adding two columns to Users: "Readonly" and "Device Readonly" (hidden by default of course)

OK. Agree, search by email will be useful.

Agree with you about way of saving. Do it only in cookies will be enough i think.

**Comment by tananaev** [comment]
Sounds good. I don't have anything against adding those columns.
