### ISSUE TITLE
Orientation state issue

### ISSUE THREAD

**Issue by Abyss777** [tananaev/traccar-web#462]
I noticed an issue on pad:
- Open Traccar Manager in vertical view (site will choose MainMobile)
- Leave both Devices and State panels collapsed
- Close application
- Open in horizontal view (site will choose Main)
- Both panels inside common panel "Devices and State" will be collapsed

I'll investigate how to handle it.

Also I'll check if it is possible change view on the fly with orientation change.

**Comment by tananaev** [comment]
Doesn't sound like a huge problem, but it would be nice to fix.
