### ISSUE TITLE
Session problem

### ISSUE THREAD

**Issue by schtack** [tananaev/traccar-web#47]
hello, i have some troubles with the web interface:

I need to clean the cache of chrome/firefox to get my device displayed on the map.

And for real time tracking on the map it's not refreshing on real time   ,the device could do some kilometers and on the map it's still on the same place. (i dont know if you understand what i want to mean...(sorry for my bad english)) 

I'm using the android app.

Thank you !

**Comment by tananaev** [comment]
Old web interface is obsolete. If this happens on the new one (Traccar 3.0+), please raise a new issue here:

https://github.com/tananaev/traccar/issues
