### ISSUE TITLE
New "Last Update" column is not ideal if clients have a time disparity with the server

### ISSUE THREAD

**Issue by stere0123** [tananaev/traccar-web#475]
Hi, I just updated to 3.11 and noticed the new Last Update column, where instead of an absolute date/time, it shows the minutes/days since last update. This is a nice idea in theory but if clients have a time disparity with the server (mainly being ahead of server time), or even if they are just updating frequently, it is not ideal.

[Example Image](https://i.imgur.com/o8P2jLK.png)

- Mainly, if points are ahead of the server time they will show -1 minutes (or more based on how offset they are).
- If points are in line with server time it will show 0 minutes, where showing the seconds would look nicer (especially for devices that update more than once every minute)
- Also, a minor note, if points are 1 minute behind server time (or one minute since last point sent) it will show "1 minutes" instead of "1 minute" which isn't correct grammar.

In these examples, showing the raw date/time of the last update could visually be more ideal. Perhaps this should be a configurable option? Thanks

**Comment by tananaev** [comment]
1. Implemented a fix for negative values.
2. I know that seconds would look nicer, but it would significantly slow down the interface because it would require refreshing every second.
3. That's a known problem, but we don't have any simple solution for it at the moment.
