### ISSUE TITLE
"Timeout (s)" and "Min. idle time (s):"

### ISSUE THREAD

**Issue by Gpsuser1234** [tananaev/traccar-web#479]
Can anyone please explain the two settings listed in the title? 

1) Timesout (S)
2) Min. idle time (s)

Kind regards

**Comment by tananaev** [comment]
Where did you see those settings? Please provide a screenshot.

**Comment by Gpsuser1234** [comment]
![skaermbillede 2017-05-03 06 33 34](https://cloud.githubusercontent.com/assets/28300958/25648269/80bb4398-2fca-11e7-8aa1-a0d9b0bf1946.png)

**Comment by tananaev** [comment]
That's not official version of Traccar.
