### ISSUE TITLE
Traccar runs fine on Localhost, but not from another pc via web

### ISSUE THREAD

**Issue by skpaul** [tananaev/traccar-web#487]
I have installed traccar on an Win7 (64) PC with a real IP. 

The service is running fine locally "http://localhost:8082/".  But not accessible from another PC via "http://182.160.99.***:8082/".

Is there any configuration needed?

**Comment by tananaev** [comment]
Have you configured firewall to allow access to the port?

**Comment by skpaul** [comment]
After configuring firewall it works now. Thanks.
