### ISSUE TITLE
Traccar Web Interface modifications

### ISSUE THREAD

**Issue by nisarzahid** [tananaev/traccar-web#489]
Hi Tananaev,

Thanks for this wonderful project. I have setup the server and web and launched it successfully by running it IntelliJIdea on localhost:8082. 
My problem is I did some modification in main interface e.g I added new button alongside + button in Device.js. Unfortunately my changes are not reflected when I re-run the project. Can you identify the possible cause? Thanks in advance.

**Comment by tananaev** [comment]
Have you compiled a minified version of the web app?

**Comment by nisarzahid** [comment]
Got the idea from your words. Commented the debug mode and use app.js instead of app.min.js in load.js file. It is working. Is this correct way of doing things in development environment?

Thank you. Bye until next hurdle.

**Comment by tananaev** [comment]
You can just open `debug.html` or add following line to the config:
```xml
<entry key='web.debug'>true</entry>
```

No code or html modifications required.
