### ISSUE TITLE
MCC/MNC/Operator

### ISSUE THREAD

**Issue by renaudallard** [tananaev/traccar-web#494]
Hello,
I see that some protocols specify the MNC/MCC they are currently on. Wouldn't it be nice to store those in the database and then be able to see the operator used by the device on the web interface? This is obviously mostly useful for roaming devices.

**Comment by tananaev** [comment]
This should be in `traccar` repository because it's related to back-end and not web app.

The easiest option would be to duplicate MCC and MNC values in the attributes.

**Comment by renaudallard** [comment]
The tables containing the operators should probably be in `traccar-web`, isn't it? Or is it better to put them in `traccar` and store the operator as an attribute?

**Comment by tananaev** [comment]
Gettings operators should be on the server side, I think. What service can we use to get it from MCC/MNC?

**Comment by renaudallard** [comment]
The ITU provides a lit when there are changes, but this is not something which changes every other day and their list cannot be easily processed of found automatically. A static list should be good enough. Perhaps a check should be made before publishing a new traccar version.

**Comment by renaudallard** [comment]
Actually, it seems the best source is still [on wikipedia](https://en.wikipedia.org/wiki/Mobile_country_code)

**Comment by renaudallard** [comment]
Or the easiest way [here](https://github.com/musalbas/mcc-mnc-table)

**Comment by renaudallard** [comment]
I will close the issue here as if the operator is stored into the attributes, it's more appropriate to open this in `traccar`
