### ISSUE TITLE
Add new category - "Tractor"

### ISSUE THREAD

**Issue by chrystianmartins** [tananaev/traccar-web#495]
hello!
Please, can you create an new "Category" to "Tractor"
Example to Image : https://maxcdn.icons8.com/Android_L/PNG/512/Transport/tractor-512.png

Thank You!

**Comment by tananaev** [comment]
We need vector images. Looks like they provide free icons for open source projects. Let's see if Traccar qualifies.

**Comment by tananaev** [comment]
Added tractor and some other new categories.

**Comment by chrystianmartins** [comment]
Thank You!!
