### ISSUE TITLE
Can i change web application to php ?

### ISSUE THREAD

**Issue by ramesh456** [tananaev/traccar-web#503]
Hi ,

I want to create my own web front end with my custom views and i am very good in PHP , html , js

So how can i write php code in this web app ?

**Comment by tananaev** [comment]
Traccar doesn't have a PHP engine. Current web interface is all HTML and JavaScript, so you should be able to understand it if you are very good at HTML and JS.

**Comment by ramesh456** [comment]
Ok. Thanks

**Comment by micheleceo** [comment]
Maybe this can help you: 
[Developed in PHP/MySQL and JavaScript]
(https://sourceforge.net/projects/gpstracking/?source=directory)
