### ISSUE TITLE
New feature suggestion

### ISSUE THREAD

**Issue by Turbovix** [tananaev/traccar-web#510]
Hello Anton, I had already talked about this subject before, however, I will mention the problem again.
In Brazil, generally the addresses use names of people, for example: (Rua Nossa Senhora do Rosário 265, Santa Paula, Vila Velha, ES, BR) which leaves the information very large, and is generally visible in an abbreviated form. It is necessary to increase the information window, ie drag right until you can see all the information.

This information is also difficult to view in Traccar Manager, even dragging the information window to the left as far as possible.

My suggestion would be to have a way to copy (Ctrl + C) the information from the address field to a possible sharing of this information, or maybe a button to share the information together with the link or a print screen of the map.

What do you think of the suggestion?

**Comment by tananaev** [comment]
It might be as simple as setting `enableTextSelection` parameter to `true`.

**Comment by Turbovix** [comment]
All this time breaking head and the answer so simple!

Thank you Anton!

**Comment by tananaev** [comment]
Note that it's a code change, not a config file parameter.

**Comment by Turbovix** [comment]
Yeah, I realized that there really is no such configuration parameter for traccar.xml (https://www.traccar.org/configuration-file/).

Can you tell me which tracar-web file to look at?

**Comment by tananaev** [comment]
Depends on what table you are talking about. If State, you should check `State.js`.

**Comment by Turbovix** [comment]
Anton, I looked for information on implementing it but found it complex, since it seems to need to be implemented for the various browsers. So I'm closing this request.
I'm going to study some JavaScript stuff.

Thank you!

**Comment by Turbovix** [comment]
I broke my mind a lot, and that was the solution!

viewConfig: {
    enableTextSelection: true
    },

Thank you!

**Comment by Turbovix** [comment]
I tested the following browsers successfully: Chrome, Firefox and Opera.

**Comment by tananaev** [comment]
Feel free to send a pull request.

**Comment by Turbovix** [comment]
I already sent the request!

Thank you!
