### ISSUE TITLE
COMMANDS from web not found - Ver 3.11

### ISSUE THREAD

**Issue by alecalabro** [tananaev/traccar-web#511]
Hello,
I installed a new server with 3.11 version and I see a lot of modifications. like Device Status, Filters to see groups and so on.. but when I tried to send a command to a TK102 Device.. I can´t find out the commands that I used in version 3.10.. line SINGLE REPORT, REPORT FREQUENCY, ETC..
Now the only command is CUSTOM COMMAND or " COMANDO PERSONALIZADO" translated to spanish.
Where can I add the rest of the commands or cound you send me the list of commands for TK102
Thanks

**Comment by tananaev** [comment]
What protocol does your device use?

**Comment by alecalabro** [comment]
HI I see GPS103 , using port 5001 on the web server.

Thanks

**Comment by alecalabro** [comment]
I reset the server and now I can see the commands.. sorry !!

**Comment by tananaev** [comment]
Closing.
