### ISSUE TITLE
Feature Request : Distance Scale on Map

### ISSUE THREAD

**Issue by MalaMusa** [tananaev/traccar-web#519]
Could you put a distance scale on map. I am using Traccar for sea and will be useful.
Thx

**Comment by tananaev** [comment]
I agree that it's probably useful functionality. There must be some existing solution available for OpenLayers that we can use.

**Comment by Abyss777** [comment]
There is ScaleLineControl http://openlayers.org/en/latest/examples/scale-line.html
@tananaev  should it be switchable or always enabled?

**Comment by tananaev** [comment]
Nice. They didn't have it before. I think we can just always enable it.
