### ISSUE TITLE
Change background color of all toolbar

### ISSUE THREAD

**Issue by jon-stumpf** [tananaev/traccar-web#528]
When changing the background-color for the toolbar-header-style to something other than #5fa22dd in app.css, the color is not applied to the collapsed Reports and Events toolbars or any of the edit toolbars.  When Event is opened, the new color is applied.  When Report is opened, the color turns "clear".

I have fixed the colors of the expanded Reports (i.e., added 'componentTls' to tbar) but I do not know CSS or Ext.js well enough to determine the right place to fix this.

I have checked Style.js and Toolbar.js and experimented but to no avail.

I will make the change if you can direct me to best place to make this "global" change.  Otherwise, I can turn this into a feature request.

**Comment by tananaev** [comment]
The right way to change colors is to create an ExtJS theme:

https://docs.sencha.com/extjs/6.2.0/guides/core_concepts/theming.html

**Comment by Ykrm** [comment]
hello tananaev, 

could you please tell me if it is possible to remove background image after user logon by using html/css or i need to add a javascript function ? if so can you share an exemple please

**Comment by tananaev** [comment]
Please don't don't comment on old closed threads.
