### ISSUE TITLE
User devices

### ISSUE THREAD

**Issue by mariostjr** [tananaev/traccar-web#53]
Im trying put a option in admin account to add device at Users accounts. 

In the function that adds a device, the code get the logged in account and create a new device to this account right?

Im trying to find the function that get the user information without sucess. Can you give me a tip? 

With this maybe i can modify the function to add a device at specify account, disable the Add, edit, rename buttons at user account and leave only at Admin account.

**Comment by tananaev** [comment]
This feature is finally implemented in version 3.2.
