### ISSUE TITLE
Feature Request: Add buttons to report generator

### ISSUE THREAD

**Issue by borozenetsvv** [tananaev/traccar-web#536]
Прошу прощения, в английском не силен. Прошу добавить кнопки "Сегодня", "Вчера", "Текущая неделя", "Текущий месяц" и т.п. в диалог "Конфигурировать" отчета "Маршрут". Не удобно каждый раз выставлять дату-вермя чтобы посмотреть пройденный маршрут.

**Comment by tananaev** [comment]
Хорошая идея. Попробуем добавить.

**Comment by Abyss777** [comment]
Хочется уточнить периоды
- Today - с 00:00 до сейчас
- Yesterday - с 00:00 вчера до 00:00 сегодня
- This week - c 00:00 дня начала недели, до сейчас (возможно затруднение с выяснением дня начала недели)
- This month - с 00:00 первого числа текущего месяца до сейчас

Какие-нибудь еще периоды?

**Comment by borozenetsvv** [comment]
Может есть смысл не "до сейчас" а до конца периода? Т.е. если "сегодня", то 00:00-23:59 и т.д.

**Comment by Abyss777** [comment]
Выглядит не очень хорошо по умолчанию

![image](https://user-images.githubusercontent.com/5688080/31212207-7f266a40-a9b8-11e7-9265-a3c5f5397fde.png)

Может есть идеи как их лучше расположить?

Есть еще вариант добавить кнопки в `date.picker` но это точно будет сложнее и действовать только на одну из дат.

![image](https://user-images.githubusercontent.com/5688080/31212252-dad97c38-a9b8-11e7-94ec-55340e7d4cd2.png)

**Comment by tananaev** [comment]
Я думаю просто еще один комбо-бокс с вариантами.
