### ISSUE TITLE
Suggestion to improve report generation

### ISSUE THREAD

**Issue by gustavofcalmeida** [tananaev/traccar-web#540]
Currently  to generate a report the user has to do this:
1. Click the reports panel to show it
2. Click "Configure"
3. Select one or more devices from the drop-down (1 click per device)
4. maybe one need to change the "From" hour.
5. Click Save
6. Two clicks to choose the report Type
7. One last click on "Show"

If the user needs to change the report parameter the steps are:
1. Click Configure
2. One click to remove old device
3. One click to add new device
4. Necessarily a click to change the "To" hour (because now it's not in the last minute)
5. click "Save"
6. Click "Show"

I think it takes too many steps. My suggestion is to make the parameter controls directly accessible from the panel. Also, use default values. Something like this:
![panel](https://user-images.githubusercontent.com/11458901/28852846-b378445a-7702-11e7-803d-a148377762f9.png)

1. Default the type of report to "Route" or other most commonly used based on poll feedback
2. No need to press "Show". Changes on the controls may trigger the "Show". At least changes in the "device", "Shortcuts" and "Dates" could do a "Clear" -> "Show".
3. Times could use [range sliders](https://jqueryui.com/slider/#range). I think the "To" could be set as default to 23:59.
4. No need to select the device. The currently selected device in the Devices panel is the one. Maybe selecting one device in devices panel automatically changes the device dropdown in reports panel. If someday the devices panel accepts multiple selection(*), no need for device dropdown at all.
5. Time range shortcuts. An easy way to setup the most common time ranges. The user selects an option in the dropdown, the dates and times get adjusted accordingly. Again, no need to click "show".

I don't know you, but I think users are more focused on the "report" that shows in the map than the lines of positions that show in the table. So, no worry losing one line of the table for the new controls.

(*) this is for another thread but, what if the user selects two or more devices and instead of centralizing the one device on the map, centralize a virtual circle that circumscribes all the selected devices? Would be great. Obviously the State panel would be unusable during multiple selection.

**Comment by tananaev** [comment]
1. There is no plan to move controls back into the toolbar because it will clutter the view.
2. I agree with shortcuts. It's nice to have an option to select last hour or day for report.
3. There is no plan to automatically request report on changing parameters. Report puts a very high load on the server and database. Unnecessary extra requests are not an option.

**Comment by tananaev** [comment]
Also, I know many businesses only care about text reports. They are not interested in map at all, so that's only your personal opinion that table doesn't matter.

**Comment by gustavofcalmeida** [comment]
If you need to click the panel, then "Configure", select a shortcut, hit "Save", then "Show", it's not a shortcut anymore.

I was planning to put this in another thread but as it would be ignored anyway let me summarize it here:
If the "Live Routes" was a dropdown icon instead of a toggle icon, and the options were similar to the ones in the shortcuts dropdown (something like 1, 3, 5 and 10 minutes OR 5, 10, 15, 20 last positions), and the result were only in the map (not report table) like it is today, I wouldn't ever bother generating a report. The main problem with live routes (in my opinion of course rs) is, it only shows the path for the positions gathered after the sign in. I think it could show the last 5 positions right form the start.

**Comment by tananaev** [comment]
I'm not sure why you think something would be ignored. There is a technical reason for it to work like that. There is no fast way to extract last 5 positions from the database.

**Comment by tananaev** [comment]
Also, I never said that shortcut has to be in the configure panel. There can be a shortcut or some combination of controls to quickly get report for currently selected device.

**Comment by gustavofcalmeida** [comment]
Seems fast to get hundreds of positions when I hit "Show".  And full positions. For the live route maybe coordinates and direction only should do. Maybe I'm delirious, but shouldn't be easy to get the last 5 points? Maybe some trick with the database that would sacrifice space in favor of speed.

What you said about the reports made me think that in fact they are for a very different purpose (still incomprehensible to me) than the one I thought. What I'm really thinking is a live route (not so live) a bit more stretched in time.

**Comment by tananaev** [comment]
The problem is that 5 last positions can be in last 5 minutes, 5 last days or even never. There are many corner cases that quickly makes it a very complicated task. I can't think of a single query that can do it, which means that we would need to run a separate SQL query for every device. User can have thousands of devices.

As for shortcuts, I was thinking that there can be a quick way to request report for currently select (in "devices" table) device. Is that what you are looking for? or do you need it for all devices? I guess all devices can be a shortcut option as well.

**Comment by Abyss777** [comment]
What is worse if we even decide construct SQL request like this:
````SQL
(SELECT * FROM positions WHERE deviceId = 1 ORDER BY fixTime DESC LIMIT 5)
UNION
(SELECT * FROM positions WHERE deviceId = 2 ORDER BY fixTime DESC LIMIT 5)
UNION
(SELECT * FROM positions WHERE deviceId = 3 ORDER BY fixTime DESC LIMIT 5)
UNION
...
````
It won't be universal because MSSQL do not have `LIMIT` but has `TOP`
