### ISSUE TITLE
Persistent Notification

### ISSUE THREAD

**Issue by jon-stumpf** [tananaev/traccar-web#548]
Is there a way to have a notification persist until the application is opened to view it/them?

I am looking for behavior like email.  The email application will put a notification icon in the "system tray" at the top of the phone to indicate that there is something to view.

**Comment by tananaev** [comment]
It's not possible at the moment.

**Comment by jon-stumpf** [comment]
Is there a limitation in the technologies employed by Traccar Manager (e.g., Ext.js) or does it simply need to be implemented?

**Comment by tananaev** [comment]
It simply needs to be implemented. If you are talking about Traccar Manager, then it's a wrong repo.

**Comment by jon-stumpf** [comment]
My apologies.  Moving to [Traccar Manager](https://github.com/tananaev/traccar-manager-android).
