### ISSUE TITLE
Duration formatting inaccurate

### ISSUE THREAD

**Issue by Abyss777** [tananaev/traccar-web#560]
Noticed the issue on screenshot not related to topic itself https://www.traccar.org/forums/topic/stops-reports-and-engine-hours/

Browser console to reproduce:
````
Traccar.AttributeFormatter.durationFormatter(7200000)
"2 h 0 m"
Traccar.AttributeFormatter.durationFormatter(7199999)
"1 h 60 m"
````

Not a big problem but "60 m" looks weird a bit

**Comment by tananaev** [comment]
Rounding issue? We can truncate instead.
