### ISSUE TITLE
feature request: fuel value in  gallons units

### ISSUE THREAD

**Issue by socstur** [tananaev/traccar-web#562]
Provide preference to show fuel values in gallons just as speed and distance has options of meters or miles.

**Comment by Abyss777** [comment]
@tananaev I think it should be ordinary field (not attribute) for consistence with speed and distance

**Comment by tananaev** [comment]
I thought about it as well, but then it's going to be polluting model. Maybe we should move existing parameters into attributes instead?

**Comment by Abyss777** [comment]
Agree that they are not so significant to be in model, but I'm not sure if we could correctly migrate DB without loosing values.

**Comment by tananaev** [comment]
I think it's OK to lose those values. Not ideal, but not worth extra effort to migrating them. They are not critical and user or admin can easily configure them again.

**Comment by Abyss777** [comment]
@tananaev what do you think about moving TimeZone to user/server attributes also?

**Comment by tananaev** [comment]
I don't mind. Is there any specific reason?

**Comment by Abyss777** [comment]
For consistence
this function https://github.com/tananaev/traccar/blob/master/src/org/traccar/database/PermissionsManager.java#L385 is used only for units and timezone. I think it is better to replace full function to lookup attributes than implement second one. Also we will avoid one "reflection using".

**Comment by tananaev** [comment]
Sounds good to me.

**Comment by Abyss777** [comment]
We have some inconsistecy in mapping context:
Here it is plural https://github.com/tananaev/traccar/blob/master/src/org/traccar/notification/NotificationFormatter.java#L51
And here it is singular
https://github.com/tananaev/traccar/blob/master/src/org/traccar/reports/ReportUtils.java#L139

It is good chance to remove inconsistency, what is better plural or singular?

**Comment by tananaev** [comment]
I think single is better.

**Comment by Abyss777** [comment]
The feature was implemented in #573
