### ISSUE TITLE
FR: Improve commands support

### ISSUE THREAD

**Issue by Abyss777** [tananaev/traccar-web#568]
Currently we have rather poor support of different commands on web side. Additional data can be submitted only for a few types. It worth to be improved.

I'm thinking of something similar to "Known Attributes" where we have store describing data and values format and dynamically change fields to fill the data.

**Comment by tananaev** [comment]
Agree, there are many commands on the back-end that are not supported in the web app because there is no way to provide parameters.

**Comment by Abyss777** [comment]
Commands was improved in #571
