### ISSUE TITLE
Feature Request: possible to deactivate by displaying flags in the status panel

### ISSUE THREAD

**Issue by netluca1** [tananaev/traccar-web#578]
Hello
Anton would it be possible to deactivate by displaying flags in the status panel some fields that are not necessary for the final customer?
Example:
Operator, Hdop, Pdop, IP, etc

**Comment by tananaev** [comment]
First of all, please change the title to reflect what the feature request is about.

As for the feature itself, I believe we have discussed it before somewhere. It is in plans to implement something like that.

**Comment by netluca1** [comment]
sorry i have edit, and thanks for your reply

**Comment by Abyss777** [comment]
@tananaev what do you think if we add some switch to state panel toolbar to hide unknown attributes (not listed in `PositionAttributes` store) as a first step of solving this issue.
It is not perfect solution, but can hide some obscure attributes like "ioXxx", "inX", "outX" firstly not translated, secondly with unknown meaning.

**Comment by tananaev** [comment]
This should be in same bucket as disabling functionality. I think attribute with option to black-list or white-list attributes is the most appropriate option. In many cases this will be configured by admin and users shouldn't have access to it.

**Comment by Abyss777** [comment]
We have some experience with comma separated attributes, but for this I would suggest regular expressions. It will be more flexible. For example we can hide all "ioXx" for teltonika in one `io\d{1,3}` expression, and we always can use `(motion|ignition)` for enumerate attributes

**Comment by tananaev** [comment]
I know regular expressions are more flexible, but they are also much slower and harder to understand for regular users.
