### ISSUE TITLE
API positions does not work

### ISSUE THREAD

**Issue by reshetnyakag** [tananaev/traccar-web#579]
Good afternoon!
After the update, the API-positions function does not work. What to do?
Server version 3.13-a clean installation, and an upgrade to version 3.14 did not help.

Добрый день!
После обновления не работает функция API - positions. Что делать?
Версия сервера 3.13 -чистая установка, а также обновление до версии 3.14 не помогло.

**Comment by tananaev** [comment]
What do you mean by doesn't work? What do you send and what do you get in response? Are you sending correct accept header?

**Comment by MacrhenkoAndrey** [comment]
When I try to open the http://SiteAddress:8082/api/positions page in the browser, I get ERR_INVALID_RESPONSE, but the http://SiteAddress:8082/api/devices page open.

При попытке открыть в браузере страницу http://SiteAddress:8082/api/positions я получаю ERR_INVALID_RESPONSE, однако страница http://SiteAddress:8082/api/devices открывается как положено.

**Comment by reshetnyakag** [comment]
When I try to open the http://SiteAddress:8082/api/positions page in the browser, I get ERR_INVALID_RESPONSE, but the http://SiteAddress:8082/api/devices page open.

При попытке открыть в браузере страницу http://SiteAddress:8082/api/positions я получаю ERR_INVALID_RESPONSE, однако страница http://SiteAddress:8082/api/devices открывается как положено.

**Comment by tananaev** [comment]
You have to provide `Accept` header as I mentioned in previous comment.

**Comment by reshetnyakag** [comment]
Indeed, the problem was in the Accept header. Thank you)

Действительно, проблема была в Accept header. Спасибо)
