### ISSUE TITLE
application settings

### ISSUE THREAD

**Issue by Jeferex** [tananaev/traccar-web#58]
Some improvements for application global settings:

The Admin can set the following settings:

1. Make a speed unit default for all users. For example: Make Km/h default for every user created. The user can change speed unit, too.

2. Default map center point

3. Default map type

**Comment by tananaev** [comment]
All the requested features (except marker colors) are available in the new web interface. Maker colors to reflect device status is planned for next release.

**Comment by bsaggarwal1** [comment]
Make a speed unit default for all users. For example: Make Km/h default for every user created. The user can change speed unit, too.
pls share procedure for achiving this?

**Comment by tananaev** [comment]
Configure corresponding attribute attribute in server settings. Please in future don't comment on closed ancient threads.
