### ISSUE TITLE
Zoom on the map using the numeric keypad

### ISSUE THREAD

**Issue by meehaanoo** [tananaev/traccar-web#584]
Hello Anton,

Is it possible to configure in a future release the zoom on the different map (Google, OpenStreeMap, ...) via + and - on the numeric keypad ?

Thank you.

**Comment by tananaev** [comment]
We'll consider it. I'm not sure how hard it is to implement such functionality.

**Comment by meehaanoo** [comment]
Hello,

If possible use the mouse wheel too ? Like on google maps :-)

Thank you,

**Comment by tananaev** [comment]
You can already use mouse wheel.

**Comment by meehaanoo** [comment]
Thank you.
