### ISSUE TITLE
Map Layers Blank and Disapper

### ISSUE THREAD

**Issue by faustinoluiz** [tananaev/traccar-web#587]
Hello, I have a fresh compiled version of traccar and work fine in last days. Today morning the map layer open street map show and after disapper and the mapview stay white. When a I click on a device in device menu, the map show but don't the marker of device/vehicles.

Someone know what happen or have a solutions?

**Comment by tananaev** [comment]
You probably have some network issues. Check browser developer console if it happens again.

**Comment by faustinoluiz** [comment]
This happen in chrome, opera, mozilla, android web view. Still not working.

**Comment by faustinoluiz** [comment]
Console have some Violation lines about ol.js.

**Comment by faustinoluiz** [comment]
I did some test and this happen only for some users. A created a user named "demo" and this work fine. This user isn't a admin. Every admin users have issue.

**Comment by tananaev** [comment]
Some violation? You have to be more specific.

**Comment by faustinoluiz** [comment]
ol.js:46 [Violation] Added non-passive event listener to a scroll-blocking 'touchstart' event. Consider marking event handler as 'passive' to make the page more responsive.
ol.js:46 [Violation] Added non-passive event listener to a scroll-blocking 'mousewheel' event. Consider marking event handler as 'passive' to make the page more responsive.
ol.js:46 [Violation] Added non-passive event listener to a scroll-blocking 'wheel' event. Consider marking event handler as 'passive' to make the page more responsive.
ol.js:46 [Violation] Added non-passive event listener to a scroll-blocking 'wheel' event. Consider marking event handler as 'passive' to make the page more responsive.
ol.js:46 [Violation] Added non-passive event listener to a scroll-blocking 'mousewheel' event. Consider marking event handler as 'passive' to make the page more responsive.
ext-all.js:22 [Violation] 'readystatechange' handler took 346ms
[Violation] Forced reflow while executing JavaScript took 39ms

This show in my console. 

I still debuging and users with less devices its working. May can be a device cause de issue.

**Comment by tananaev** [comment]
I think those can be safely ignored. What about network tab. Are tiles loading normally?

**Comment by faustinoluiz** [comment]
Everting is ok. I think than this issue have link with te openlayers. But, I still waiting a connection from device to confirm the solution. I'm just don't known why its happen.

**Comment by ninioe** [comment]
Hi,
I also have this problem. It was working fine and than the map dissaper.
How can I solve this?

Thanks
Erez

**Comment by ninioe** [comment]
I solve it by changing the user map, it was on Bing with no key and override the server default map.

Thanks
Erez

**Comment by faustinoluiz** [comment]
Very, very strangh this issue.
