### ISSUE TITLE
Multiline State Panel cells

### ISSUE THREAD

**Issue by Abyss777** [tananaev/traccar-web#607]
Actually making cell "selectable" #603 did not help initial problem (impossible read long data in grid cells)
Only visible data are selectable, cut strings are cut in clipboard. 

What do you think of making state grid multiline?

![image](https://user-images.githubusercontent.com/5688080/31875405-741bf3a8-b7e7-11e7-8b83-63bd5a0216dd.png)

**Comment by tananaev** [comment]
Looks OK to me.
