### ISSUE TITLE
devices not showing on the map

### ISSUE THREAD

**Issue by jiiihen** [tananaev/traccar-web#613]
Hello
i installed traccar-server on a debian server and it's working. I created an user with 4 devices, the positions are registred in the data base (for the 4 devices) and the web interface show them as online.
But when  only one is showing on the map (when i clic on the others nothing happen)
![web](https://user-images.githubusercontent.com/5587030/32217156-680c7ba0-be27-11e7-8333-d7823319fcf8.png)
Thanks.

**Comment by tananaev** [comment]
It means there is no location data from those devices.

**Comment by jiiihen** [comment]
you mean latitude and longitude ?

**Comment by tananaev** [comment]
Is it the same device?

**Comment by jiiihen** [comment]
this is the "156 TU 745" it's show on line but no marker on the map.

**Comment by tananaev** [comment]
Can I have access to the system to take a look myself?

**Comment by jiiihen** [comment]
ok thanks.
web server: http://196.203.148.27:8015/
user: afrimed@impactcontact.tn / userafrimed
admin: default

**Comment by tananaev** [comment]
It looks like you are not using official version. That should be the first thing to mention when you open an issue. In fact you should not open an issue unless it's also reproducible on official Traccar.

**Comment by jiiihen** [comment]
i didn't uderstand it's dowloaded from this github

**Comment by tananaev** [comment]
Have you modified anything after downloading it from this github repo?
