### ISSUE TITLE
Safari dialog boxes problem

### ISSUE THREAD

**Issue by kruzhkov** [tananaev/traccar-web#618]
Добрый день Антон

В окнах редактирования свойств в Safari не отображается наименование группы, соответственно невозможно раскрыть дополнительные свойства, те что под +

![2017-11-07 15 45 31](https://user-images.githubusercontent.com/30497843/32495017-e92230d8-c3d4-11e7-9593-add28a7de1c6.png)

**Comment by tananaev** [comment]
Это известная проблема и она уже исправлена. Ждите новой версии.
