### ISSUE TITLE
Right event pane not updating on master branch

### ISSUE THREAD

**Issue by Shinryuken** [tananaev/traccar-web#619]
Hi,

Looks like that the Events pane on the right of the user interface is not udating, i can see events coming but no elements are added on it.

It's working on release 3.14

**Comment by tananaev** [comment]
I have just tested with latest code and it works for me. Are you sure you have enabled web notifications for the user?

**Comment by Shinryuken** [comment]
i noticed now that i was using a wrong setup, i rebuilt it from scratch and it's working, i'm closing it
