### ISSUE TITLE
Cant send mail...

### ISSUE THREAD

**Issue by pareliuss** [tananaev/traccar-web#627]
After fresh 3.15 install, i cant send mail.

I get this error:

<img width="188" alt="skjermbilde" src="https://user-images.githubusercontent.com/25965138/33798463-d53c0c4e-dd18-11e7-93b3-102ebd008c5f.PNG">

This is my settings:

<img width="415" alt="skjermbilde1" src="https://user-images.githubusercontent.com/25965138/33798498-c2e59b90-dd19-11e7-8218-ba8ced0be777.PNG">

**Comment by tananaev** [comment]
Are you using official release without any modifications to config or source code?

**Comment by pareliuss** [comment]
Yes, orginal version with no mods.

**Comment by tananaev** [comment]
Try to re-download it again. I have fixed the problem.

**Comment by pareliuss** [comment]
Reinstalled, but i got a new error:

<img width="249" alt="skjermbilde3" src="https://user-images.githubusercontent.com/25965138/33799401-25e11c5e-dd2b-11e7-940c-4e9a4f23e7fb.PNG">

**Comment by tananaev** [comment]
You should probably copy the whole error here instead of pasting screenshot that cuts most of the useful information.

**Comment by pareliuss** [comment]
sorry, 

java.lang.Boolean cannot be cast to java.lang.String - ClassCastException (ExtendedModel:89 < PropertiesProvider:39 < NotificationMail:57 < ...)

**Comment by tananaev** [comment]
Attribute `mail.smtp.ssl.enable` should be a string, not boolean.

**Comment by pareliuss** [comment]
Working now.

Thank you :)
