### ISSUE TITLE
Change Io1 TK103 attribute name.

### ISSUE THREAD

**Issue by cnavarrog** [tananaev/traccar-web#629]
Regards
With old versions, i was abble to change an attribute name to certain value, with this version i dont understand how change o add an attribute base for example on Io1 value for Tk103a 

Could you provide me please an example ?
Io1 value = 1 then 'Door open'
Io1 Value = 0 then 'Door Close'

thanks in advance.

**Comment by tananaev** [comment]
You can create new computed attribute with any name you want. Either way, the right place to ask questions like this is forum, not GitHub.
