### ISSUE TITLE
suggest the install file can include all the resource

### ISSUE THREAD

**Issue by sznova** [tananaev/traccar-web#632]
when finish install the traccar server , and open the website of traccar , it will download some file from other website, such as js file from cdnjs.cloudflare.com/ajax/libs/extjs/6.2.0/ext-all.js" and so on.

because when I am in china, the speed of cloudflare.com is very slow.
So I wish the installer of server file can include all the js file or other file that from other website.
Then the speed of web interface will be fast.
Thanks

**Comment by tananaev** [comment]
I don't agree with this one. It would make life more complicated for everyone.

I suggest you come up with a script that would do it automatically.

**Comment by sznova** [comment]
hello, do you know how to develop the script will do it automatically?

**Comment by tananaev** [comment]
I probably do. Do you want to sponsor this script?

**Comment by sznova** [comment]
Thanks for answer.
