### ISSUE TITLE
Device windows hangs with 'Loading...'

### ISSUE THREAD

**Issue by caveman99** [tananaev/traccar-web#641]
Installed the server with mysql db, connected an app, transmitted a few coordinates. Now when i log in the Device window does not finish loading. The Debugger shows the content just coming back fine, but there seems to be an error in the return values, so they never get displayed.

Request returns:
```json
[null,{"id":2,"attributes":{},"name":"Telefon","uniqueId":"570633","status":"offline","lastUpdate":"2018-01-16T20:22:39.000+0000","positionId":448,"groupId":1,"geofenceIds":[],"phone":"","model":"","contact":"","category":"person","disabled":false}]
```
Error Console shows (not sure this is really related): 
```
Uncaught TypeError: Cannot read property 'isModel' of null
    at F.extractData (ext-all.js:22)
    at F.extractData (ext-all.js:22)
    at F.readRecords (ext-all.js:22)
    at F.read (ext-all.js:22)
    at F.processResponse (ext-all.js:22)
    at F.<anonymous> (ext-all.js:22)
    at Object.callback (ext-all.js:22)
    at F.onComplete (ext-all.js:22)
    at F.onStateChange (ext-all.js:22)
    at XMLHttpRequest.<anonymous> (ext-all.js:22)
```
but the request thst turns up this error is /api/attributes/computed?_dc=1516136404433&page=1&start=0&limit=25 instead of the suspect /api/attributes/devices?_dc=1516136404536&page=1&start=0&limit=25

**Comment by tananaev** [comment]
Are you using MyISAM engine?

**Comment by caveman99** [comment]
I created the empty database with default innodb and let the backend create the tables, hoping they would be innodb automatically. They seem to have been created in myisam :-(

After a couple of alter table statements the app still does not wqork. Do i need to clear out table data?

**Comment by tananaev** [comment]
If tables were created with MyISAM it means that default was MyISAM. Changing tables won't help because you are missing proper foreign key constraints. You would need to re-create database with InnoDB engine.

**Comment by caveman99** [comment]
I finally realized this was (very outdated) mysql 5.1 with a default of MyISAM. After forcing innodb and recreating tables it worked out of the box. Thanks again and sorry for the bother.
