### ISSUE TITLE
Notifications

### ISSUE THREAD

**Issue by Globocopias** [tananaev/traccar-web#648]
![notificacao](https://user-images.githubusercontent.com/36344109/36067440-6febbff2-0ea4-11e8-80df-73b4e8f09480.jpg)

Hi, could you delete the notices that are repeated ??
Do you have a configuration file where you can exclude notices that are the same?

**Comment by tananaev** [comment]
You need to remove then yourself from Settings > Notifications menu.

Please use forum for questions. Github is only for feature requests and development-related discussions.
