### ISSUE TITLE
Lost DB connection?

### ISSUE THREAD

**Issue by ptrlv** [tananaev/traccar-web#65]
I see this error in wrapper.log  https://gist.github.com/ptrlv/5684103

This occurs when logging into the web interface. A user/pass error is given which I assume is due to lack of DB connection. I'm using mysql backend. Should the web interface reconnect to the DB automatically? Or perhaps the question should be what is causing the lost connection?

**Comment by tananaev** [comment]
Old web interface is obsolete. If new web interface has same/similar issue, please report it here:

https://github.com/tananaev/traccar/issues
