### ISSUE TITLE
Issue with group notifications

### ISSUE THREAD

**Issue by tananaev** [tananaev/traccar-web#651]
Looks like admin can see all notifications when linking notifications to groups from the Settings > Groups > Notifications menu.

@Abyss777, do you think it's a bug or is there any specific reason we implement it like this?

**Comment by Abyss777** [comment]
Good question, frankly I do not know. We have the same logic for linking all Group objects.
https://github.com/tananaev/traccar-web/blob/master/web/app/view/edit/GroupsController.js
```js
storeName: admin ? 'AllGeofences' : 'Geofences',
```

Agree, it is not consistent, we have either remove this logic from groups or add it to devices logic too

**Comment by tananaev** [comment]
Do you remember why we did it? It probably makes sense to just show admin geofences/notifications/etc, like in all other places.

**Comment by Abyss777** [comment]
I could not recall why we did it and do not see any reason. So we can close the issue.
