### ISSUE TITLE
WKT parser could be wrong

### ISSUE THREAD

**Issue by kgrosvenor** [tananaev/traccar-web#653]
Im using a tracaar server in a project of mine,  tried to parse using wellknown/mapbox and the polygons lat and lng are the wrong way round... but displayed correctly on openlayers in this project - not sure if this is an issue with leaflet, or the way tracaar web client is sending area to the server.

**Comment by kgrosvenor** [comment]
gonna close, because its not directly related to any issues in this app - feel free to talk though, i've found a work around but its very odd! 

Thanks :)

**Comment by tananaev** [comment]
This issue has been raised before:

https://www.traccar.org/forums/topic/wkt-format-pointlatlng-or-pointlnglat/

Basically there is no standard around order of the coordinates. Traccar uses less common order, so it might be incompatible with some WTK tools.

**Comment by kgrosvenor** [comment]
thanks for the response, i found a work around in the end, lats and long were just the wrong way ='[ aha !
