### ISSUE TITLE
Веб-интерфейс

### ISSUE THREAD

**Issue by team-core** [tananaev/traccar-web#657]
Здравствуйте, Антон
не подскажете, в чем дело?
Инсталлировал для клиента traccar, согласно этому туториалу:
https://www.traccar.org/install-digitalocean/

В конце сказано идти на ИП сервера, что бы попасть в веб-интерфейс. Но там Unable to connect и я делаю выывод, что либо нет интерфеса, либо что-то пошло не так. В форуме и тут прочел, что все же по дефолту веб-интерфейс идет с софтом. Подскажите, куда смотреть и что дергать?
Спасибо.

**Comment by tananaev** [comment]
Смотрите логи сервера. Сервер точно работает и локально слушает порты? Если да, то возможно проблема с файрволом.

**Comment by team-core** [comment]
фаервол пока пустой, все дефолтно, насколько возможно

**Comment by team-core** [comment]
в логах только инсталляционная и первоначальная инфа

**Comment by team-core** [comment]
Полез в Базу данных. Это странно?
mysql> USE traccar;
Database changed
mysql> SHOW tables;
Empty set (0.00 sec)

mysql>

**Comment by tananaev** [comment]
Если туториал выполнить один в один, то точно все должно работать. Если не работает значит что-то пропустили или неправильно сделали. Смотрите конфигурацию например.

**Comment by team-core** [comment]
Один в один. Только ВПС свой.
Конфигурацию чего смотреть? 
Может дать доступ? )

**Comment by tananaev** [comment]
Загружайте логи и конфиги сюда и посмотрим что за проблема. Только как файлы грузите, а не текстом в пост.

**Comment by team-core** [comment]
[traccar.zip](https://github.com/tananaev/traccar-web/files/1828930/traccar.zip)

ну вот, если я правильно понимаю

**Comment by team-core** [comment]
странным образом само заработало...

**Comment by tananaev** [comment]
Тогда закрываем issue.

**Comment by team-core** [comment]
да
