### ISSUE TITLE
Secure Connection

### ISSUE THREAD

**Issue by team-core** [tananaev/traccar-web#658]
Здравствуйте, Антон
Опять вынужден обратиться к вам.
Стандартный сервер, стандартный инсталл по вашим докам. (Убунту 16.04). Если помните, это тот самый сервер, что обсуждался тут: https://github.com/tananaev/traccar-web/issues/657

Дошли до сертификатов. опять же, сделано все по доку:
https://www.traccar.org/secure-connection/

На шаге генерации сертификата выбираем апач+убунту 16.04
https://certbot.eff.org/lets-encrypt/ubuntuxenial-apache

Добираемся до команды $ sudo certbot --apache и получаем вывод в приложении
[output.txt](https://github.com/tananaev/traccar-web/files/1836408/output.txt)

Обращался в сторонюю поддержку, тк по ощущениям, апач не запускался, хотя и не выдавал ошибок. Они Апач запустили, порт для http соединений - 81, на 80 порту висит jetty.
Пробую еще раз, вывод уже поинтереснее, но все равно мимо:
[output2.txt](https://github.com/tananaev/traccar-web/files/1836420/output2.txt)

Сторонняя поддержка еще прокомментировала дело так:
Либо в процессе установки была допущена ошибка, либо не могу считать этот гайд рабочим.
При запуске certbot он автоматически вписывает в ports.conf 80 порт для не зашифрованных соединений, отсюда мы и получаем эту ошибку.

Насколько я понимаю для certbot требуется именно *80 порт.
Если изменить конфиг /etc/apache2/sites-enabled/000-default.conf с указанием *81 порта, видим следующее -

Unable to find a virtual host listening on port 80 which is currently needed for Certbot to prove to the CA that you control your domain. Please add a virtual host for port 80.

Конфликт налицо. К сожалению затрудняюсь проконсультировать вас в данной ситуации. По логике апач и должен продолжать работать на 80 порту, без изменений.
Изменения сделанные мной, откатили.

После чего откатили свои изменения и я остался там, с чего начал.

Могли бы вы прокомментировать? 
Спасибо!

**Comment by tananaev** [comment]
Похоже что у вас уже что-то висит на 80 порту. Смотрите что за процесс его занимает.

**Comment by team-core** [comment]
Я так понимаю, java
java     1502  root  394u  IPv6 41237254      0t0  TCP *:80 (LISTEN)

Ничего специально нигде не менялось, все стандартно, повторюсь.

**Comment by tananaev** [comment]
Похоже что у вас Traccar занимает 80 порт.

**Comment by team-core** [comment]
Хорошо. Как я полагаю, это произошло в результате стандартных шагов по хау-ту. А что надо делать теперь? Как натянуть ССЛ? Как обойти эту коллизию?

**Comment by tananaev** [comment]
Поменяйте порт в Traccar. Либо временно либо на постоянно.

**Comment by team-core** [comment]
Хорошо. А как? Единственное, что я знаю - он находится в папке /opt...

**Comment by tananaev** [comment]
Считайте официальную документацию. Там все есть.

**Comment by team-core** [comment]
Если это файл traccar.xml, то в нем есть такое:
    <entry key='web.port'>80</entry>
Какой выбрать?

**Comment by team-core** [comment]
В общем, вопрос бы не встал, если бы в данном доке 
https://www.traccar.org/install-digitalocean/
в разделе Example configuration (replace password if needed) в примере конфига был сразу указан правильный порт.
