### ISSUE TITLE
Show popup when choosing spot on the map

### ISSUE THREAD

**Issue by robertoalmeida** [tananaev/traccar-web#71]
You can show a popup when you click a point on the map with information of date, speed, latitude, longitude and more?

I think one interesting feature.

I made a montage of the example.

![captura de tela 2013-06-05 as 22 59 39](https://f.cloud.github.com/assets/4574415/616045/62da1428-ce56-11e2-8d4c-bae82c75b144.png)

**Comment by tananaev** [comment]
There is no plan to implement it at the moment.
