### ISSUE TITLE
Columns in tables (web)

### ISSUE THREAD

**Issue by RaulBernal** [tananaev/traccar-web#77]
Hello, 

for a debug enviroment, some columns in tables may be usefull but in a production enviroment not.

In example, the column 'valid' would be hidden and 'altitude' if it not supported also.

I have hidden some columns from 'Archive' table but when reload sessions I lost the changes.
There are any way to fix it? Thank's

**Comment by tananaev** [comment]
Closing this as stale. Please reopen if it's still valid.
