### ISSUE TITLE
Create setup for windows

### ISSUE THREAD

**Issue by AlejoCR** [tananaev/traccar-web#91]
Hi, I've followed all steps to create a setup file for windows, but I always get errors when I run package.sh and I only get a zip with reademe text. I don't know if I have to create other files before to run package.sh or where to put in it, I've already create traccar-web.war, but I get errors saying something about deploy and lib path, I'm using the files as I've downloaded it from this page

I have a makeself zip warning  saying that "name no matched ../target/traccar-server.jar". Which jar file is it? What path is it? Afther that I have more error, but all are about files not found and missing paths

**Comment by tananaev** [comment]
Old web interface is obsolete. New web interface is written in pure JavaScript. For information about building project from source see following page:

https://www.traccar.org/build/
